/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaCategorymetas implements Serializable {

    private static final long serialVersionUID = -1614624311;

    private UInteger categoryid;
    private String   title;
    private String   content;

    public QaCategorymetas() {}

    public QaCategorymetas(QaCategorymetas value) {
        this.categoryid = value.categoryid;
        this.title = value.title;
        this.content = value.content;
    }

    public QaCategorymetas(
        UInteger categoryid,
        String   title,
        String   content
    ) {
        this.categoryid = categoryid;
        this.title = title;
        this.content = content;
    }

    public UInteger getCategoryid() {
        return this.categoryid;
    }

    public void setCategoryid(UInteger categoryid) {
        this.categoryid = categoryid;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaCategorymetas (");

        sb.append(categoryid);
        sb.append(", ").append(title);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
