/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaCache implements Serializable {

    private static final long serialVersionUID = -260569247;

    private String    type;
    private ULong     cacheid;
    private byte[]    content;
    private Timestamp created;
    private Timestamp lastread;

    public QaCache() {}

    public QaCache(QaCache value) {
        this.type = value.type;
        this.cacheid = value.cacheid;
        this.content = value.content;
        this.created = value.created;
        this.lastread = value.lastread;
    }

    public QaCache(
        String    type,
        ULong     cacheid,
        byte[]    content,
        Timestamp created,
        Timestamp lastread
    ) {
        this.type = type;
        this.cacheid = cacheid;
        this.content = content;
        this.created = created;
        this.lastread = lastread;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public ULong getCacheid() {
        return this.cacheid;
    }

    public void setCacheid(ULong cacheid) {
        this.cacheid = cacheid;
    }

    public byte[] getContent() {
        return this.content;
    }

    public void setContent(byte... content) {
        this.content = content;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getLastread() {
        return this.lastread;
    }

    public void setLastread(Timestamp lastread) {
        this.lastread = lastread;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaCache (");

        sb.append(type);
        sb.append(", ").append(cacheid);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(created);
        sb.append(", ").append(lastread);

        sb.append(")");
        return sb.toString();
    }
}
