/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.enums.QaMessagesType;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaMessages implements Serializable {

    private static final long serialVersionUID = 621259653;

    private UInteger       messageid;
    private QaMessagesType type;
    private UInteger       fromuserid;
    private UInteger       touserid;
    private UByte          fromhidden;
    private UByte          tohidden;
    private String         content;
    private String         format;
    private Timestamp      created;

    public QaMessages() {}

    public QaMessages(QaMessages value) {
        this.messageid = value.messageid;
        this.type = value.type;
        this.fromuserid = value.fromuserid;
        this.touserid = value.touserid;
        this.fromhidden = value.fromhidden;
        this.tohidden = value.tohidden;
        this.content = value.content;
        this.format = value.format;
        this.created = value.created;
    }

    public QaMessages(
        UInteger       messageid,
        QaMessagesType type,
        UInteger       fromuserid,
        UInteger       touserid,
        UByte          fromhidden,
        UByte          tohidden,
        String         content,
        String         format,
        Timestamp      created
    ) {
        this.messageid = messageid;
        this.type = type;
        this.fromuserid = fromuserid;
        this.touserid = touserid;
        this.fromhidden = fromhidden;
        this.tohidden = tohidden;
        this.content = content;
        this.format = format;
        this.created = created;
    }

    public UInteger getMessageid() {
        return this.messageid;
    }

    public void setMessageid(UInteger messageid) {
        this.messageid = messageid;
    }

    public QaMessagesType getType() {
        return this.type;
    }

    public void setType(QaMessagesType type) {
        this.type = type;
    }

    public UInteger getFromuserid() {
        return this.fromuserid;
    }

    public void setFromuserid(UInteger fromuserid) {
        this.fromuserid = fromuserid;
    }

    public UInteger getTouserid() {
        return this.touserid;
    }

    public void setTouserid(UInteger touserid) {
        this.touserid = touserid;
    }

    public UByte getFromhidden() {
        return this.fromhidden;
    }

    public void setFromhidden(UByte fromhidden) {
        this.fromhidden = fromhidden;
    }

    public UByte getTohidden() {
        return this.tohidden;
    }

    public void setTohidden(UByte tohidden) {
        this.tohidden = tohidden;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getFormat() {
        return this.format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaMessages (");

        sb.append(messageid);
        sb.append(", ").append(type);
        sb.append(", ").append(fromuserid);
        sb.append(", ").append(touserid);
        sb.append(", ").append(fromhidden);
        sb.append(", ").append(tohidden);
        sb.append(", ").append(content);
        sb.append(", ").append(format);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
