/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaPostmetas implements Serializable {

    private static final long serialVersionUID = 1358204983;

    private UInteger postid;
    private String   title;
    private String   content;

    public QaPostmetas() {}

    public QaPostmetas(QaPostmetas value) {
        this.postid = value.postid;
        this.title = value.title;
        this.content = value.content;
    }

    public QaPostmetas(
        UInteger postid,
        String   title,
        String   content
    ) {
        this.postid = postid;
        this.title = title;
        this.content = content;
    }

    public UInteger getPostid() {
        return this.postid;
    }

    public void setPostid(UInteger postid) {
        this.postid = postid;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaPostmetas (");

        sb.append(postid);
        sb.append(", ").append(title);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
