/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaPosttags implements Serializable {

    private static final long serialVersionUID = -1948255901;

    private UInteger  postid;
    private UInteger  wordid;
    private Timestamp postcreated;

    public QaPosttags() {}

    public QaPosttags(QaPosttags value) {
        this.postid = value.postid;
        this.wordid = value.wordid;
        this.postcreated = value.postcreated;
    }

    public QaPosttags(
        UInteger  postid,
        UInteger  wordid,
        Timestamp postcreated
    ) {
        this.postid = postid;
        this.wordid = wordid;
        this.postcreated = postcreated;
    }

    public UInteger getPostid() {
        return this.postid;
    }

    public void setPostid(UInteger postid) {
        this.postid = postid;
    }

    public UInteger getWordid() {
        return this.wordid;
    }

    public void setWordid(UInteger wordid) {
        this.wordid = wordid;
    }

    public Timestamp getPostcreated() {
        return this.postcreated;
    }

    public void setPostcreated(Timestamp postcreated) {
        this.postcreated = postcreated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaPosttags (");

        sb.append(postid);
        sb.append(", ").append(wordid);
        sb.append(", ").append(postcreated);

        sb.append(")");
        return sb.toString();
    }
}
