/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaTopics implements Serializable {

    private static final long serialVersionUID = 433505408;

    private Integer id;
    private String  topic;

    public QaTopics() {}

    public QaTopics(QaTopics value) {
        this.id = value.id;
        this.topic = value.topic;
    }

    public QaTopics(
        Integer id,
        String  topic
    ) {
        this.id = id;
        this.topic = topic;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTopic() {
        return this.topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaTopics (");

        sb.append(id);
        sb.append(", ").append(topic);

        sb.append(")");
        return sb.toString();
    }
}
