/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserpoints implements Serializable {

    private static final long serialVersionUID = 527235690;

    private String  userid;
    private Integer points;
    private Integer qposts;
    private Integer aposts;
    private Integer cposts;
    private Integer aselects;
    private Integer aselecteds;
    private Integer qupvotes;
    private Integer qdownvotes;
    private Integer aupvotes;
    private Integer adownvotes;
    private Integer qvoteds;
    private Integer avoteds;
    private Integer upvoteds;
    private Integer downvoteds;
    private Integer bonus;

    public QaUserpoints() {}

    public QaUserpoints(QaUserpoints value) {
        this.userid = value.userid;
        this.points = value.points;
        this.qposts = value.qposts;
        this.aposts = value.aposts;
        this.cposts = value.cposts;
        this.aselects = value.aselects;
        this.aselecteds = value.aselecteds;
        this.qupvotes = value.qupvotes;
        this.qdownvotes = value.qdownvotes;
        this.aupvotes = value.aupvotes;
        this.adownvotes = value.adownvotes;
        this.qvoteds = value.qvoteds;
        this.avoteds = value.avoteds;
        this.upvoteds = value.upvoteds;
        this.downvoteds = value.downvoteds;
        this.bonus = value.bonus;
    }

    public QaUserpoints(
        String  userid,
        Integer points,
        Integer qposts,
        Integer aposts,
        Integer cposts,
        Integer aselects,
        Integer aselecteds,
        Integer qupvotes,
        Integer qdownvotes,
        Integer aupvotes,
        Integer adownvotes,
        Integer qvoteds,
        Integer avoteds,
        Integer upvoteds,
        Integer downvoteds,
        Integer bonus
    ) {
        this.userid = userid;
        this.points = points;
        this.qposts = qposts;
        this.aposts = aposts;
        this.cposts = cposts;
        this.aselects = aselects;
        this.aselecteds = aselecteds;
        this.qupvotes = qupvotes;
        this.qdownvotes = qdownvotes;
        this.aupvotes = aupvotes;
        this.adownvotes = adownvotes;
        this.qvoteds = qvoteds;
        this.avoteds = avoteds;
        this.upvoteds = upvoteds;
        this.downvoteds = downvoteds;
        this.bonus = bonus;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public Integer getPoints() {
        return this.points;
    }

    public void setPoints(Integer points) {
        this.points = points;
    }

    public Integer getQposts() {
        return this.qposts;
    }

    public void setQposts(Integer qposts) {
        this.qposts = qposts;
    }

    public Integer getAposts() {
        return this.aposts;
    }

    public void setAposts(Integer aposts) {
        this.aposts = aposts;
    }

    public Integer getCposts() {
        return this.cposts;
    }

    public void setCposts(Integer cposts) {
        this.cposts = cposts;
    }

    public Integer getAselects() {
        return this.aselects;
    }

    public void setAselects(Integer aselects) {
        this.aselects = aselects;
    }

    public Integer getAselecteds() {
        return this.aselecteds;
    }

    public void setAselecteds(Integer aselecteds) {
        this.aselecteds = aselecteds;
    }

    public Integer getQupvotes() {
        return this.qupvotes;
    }

    public void setQupvotes(Integer qupvotes) {
        this.qupvotes = qupvotes;
    }

    public Integer getQdownvotes() {
        return this.qdownvotes;
    }

    public void setQdownvotes(Integer qdownvotes) {
        this.qdownvotes = qdownvotes;
    }

    public Integer getAupvotes() {
        return this.aupvotes;
    }

    public void setAupvotes(Integer aupvotes) {
        this.aupvotes = aupvotes;
    }

    public Integer getAdownvotes() {
        return this.adownvotes;
    }

    public void setAdownvotes(Integer adownvotes) {
        this.adownvotes = adownvotes;
    }

    public Integer getQvoteds() {
        return this.qvoteds;
    }

    public void setQvoteds(Integer qvoteds) {
        this.qvoteds = qvoteds;
    }

    public Integer getAvoteds() {
        return this.avoteds;
    }

    public void setAvoteds(Integer avoteds) {
        this.avoteds = avoteds;
    }

    public Integer getUpvoteds() {
        return this.upvoteds;
    }

    public void setUpvoteds(Integer upvoteds) {
        this.upvoteds = upvoteds;
    }

    public Integer getDownvoteds() {
        return this.downvoteds;
    }

    public void setDownvoteds(Integer downvoteds) {
        this.downvoteds = downvoteds;
    }

    public Integer getBonus() {
        return this.bonus;
    }

    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaUserpoints (");

        sb.append(userid);
        sb.append(", ").append(points);
        sb.append(", ").append(qposts);
        sb.append(", ").append(aposts);
        sb.append(", ").append(cposts);
        sb.append(", ").append(aselects);
        sb.append(", ").append(aselecteds);
        sb.append(", ").append(qupvotes);
        sb.append(", ").append(qdownvotes);
        sb.append(", ").append(aupvotes);
        sb.append(", ").append(adownvotes);
        sb.append(", ").append(qvoteds);
        sb.append(", ").append(avoteds);
        sb.append(", ").append(upvoteds);
        sb.append(", ").append(downvoteds);
        sb.append(", ").append(bonus);

        sb.append(")");
        return sb.toString();
    }
}
