/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUsernotices implements Serializable {

    private static final long serialVersionUID = -1019338163;

    private UInteger  noticeid;
    private String    userid;
    private String    content;
    private String    format;
    private String    tags;
    private Timestamp created;

    public QaUsernotices() {}

    public QaUsernotices(QaUsernotices value) {
        this.noticeid = value.noticeid;
        this.userid = value.userid;
        this.content = value.content;
        this.format = value.format;
        this.tags = value.tags;
        this.created = value.created;
    }

    public QaUsernotices(
        UInteger  noticeid,
        String    userid,
        String    content,
        String    format,
        String    tags,
        Timestamp created
    ) {
        this.noticeid = noticeid;
        this.userid = userid;
        this.content = content;
        this.format = format;
        this.tags = tags;
        this.created = created;
    }

    public UInteger getNoticeid() {
        return this.noticeid;
    }

    public void setNoticeid(UInteger noticeid) {
        this.noticeid = noticeid;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getFormat() {
        return this.format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getTags() {
        return this.tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaUsernotices (");

        sb.append(noticeid);
        sb.append(", ").append(userid);
        sb.append(", ").append(content);
        sb.append(", ").append(format);
        sb.append(", ").append(tags);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
