/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserlimits implements Serializable {

    private static final long serialVersionUID = 1418745760;

    private String   userid;
    private String   action;
    private UInteger period;
    private UShort   count;

    public QaUserlimits() {}

    public QaUserlimits(QaUserlimits value) {
        this.userid = value.userid;
        this.action = value.action;
        this.period = value.period;
        this.count = value.count;
    }

    public QaUserlimits(
        String   userid,
        String   action,
        UInteger period,
        UShort   count
    ) {
        this.userid = userid;
        this.action = action;
        this.period = period;
        this.count = count;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public UInteger getPeriod() {
        return this.period;
    }

    public void setPeriod(UInteger period) {
        this.period = period;
    }

    public UShort getCount() {
        return this.count;
    }

    public void setCount(UShort count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaUserlimits (");

        sb.append(userid);
        sb.append(", ").append(action);
        sb.append(", ").append(period);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
