/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserlogins implements Serializable {

    private static final long serialVersionUID = 1471526108;

    private UInteger userid;
    private String   source;
    private byte[]   identifier;
    private byte[]   identifiermd5;
    private String   oemail;
    private String   ohandle;

    public QaUserlogins() {}

    public QaUserlogins(QaUserlogins value) {
        this.userid = value.userid;
        this.source = value.source;
        this.identifier = value.identifier;
        this.identifiermd5 = value.identifiermd5;
        this.oemail = value.oemail;
        this.ohandle = value.ohandle;
    }

    public QaUserlogins(
        UInteger userid,
        String   source,
        byte[]   identifier,
        byte[]   identifiermd5,
        String   oemail,
        String   ohandle
    ) {
        this.userid = userid;
        this.source = source;
        this.identifier = identifier;
        this.identifiermd5 = identifiermd5;
        this.oemail = oemail;
        this.ohandle = ohandle;
    }

    public UInteger getUserid() {
        return this.userid;
    }

    public void setUserid(UInteger userid) {
        this.userid = userid;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public byte[] getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(byte... identifier) {
        this.identifier = identifier;
    }

    public byte[] getIdentifiermd5() {
        return this.identifiermd5;
    }

    public void setIdentifiermd5(byte... identifiermd5) {
        this.identifiermd5 = identifiermd5;
    }

    public String getOemail() {
        return this.oemail;
    }

    public void setOemail(String oemail) {
        this.oemail = oemail;
    }

    public String getOhandle() {
        return this.ohandle;
    }

    public void setOhandle(String ohandle) {
        this.ohandle = ohandle;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QaUserlogins (");

        sb.append(userid);
        sb.append(", ").append(source);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(oemail);
        sb.append(", ").append(ohandle);

        sb.append(")");
        return sb.toString();
    }
}
