/*
 * This file is generated by jOOQ.
*/
package DBnewLogrExtra.tables.daos;


import DBnewLogrExtra.tables.pojos.Permissions;
import DBnewLogrExtra.tables.records.PermissionsRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionsDao extends DAOImpl<PermissionsRecord, Permissions, Integer> {

    /**
     * Create a new PermissionsDao without any configuration
     */
    public PermissionsDao() {
        super(DBnewLogrExtra.tables.Permissions.PERMISSIONS, Permissions.class);
    }

    /**
     * Create a new PermissionsDao with an attached configuration
     */
    public PermissionsDao(Configuration configuration) {
        super(DBnewLogrExtra.tables.Permissions.PERMISSIONS, Permissions.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(Permissions object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<Permissions> fetchById(Integer... values) {
        return fetch(DBnewLogrExtra.tables.Permissions.PERMISSIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Permissions fetchOneById(Integer value) {
        return fetchOne(DBnewLogrExtra.tables.Permissions.PERMISSIONS.ID, value);
    }

    /**
     * Fetch records that have <code>roleid IN (values)</code>
     */
    public List<Permissions> fetchByRoleid(Integer... values) {
        return fetch(DBnewLogrExtra.tables.Permissions.PERMISSIONS.ROLEID, values);
    }

    /**
     * Fetch records that have <code>routeid IN (values)</code>
     */
    public List<Permissions> fetchByRouteid(Integer... values) {
        return fetch(DBnewLogrExtra.tables.Permissions.PERMISSIONS.ROUTEID, values);
    }

    /**
     * Fetch records that have <code>permit IN (values)</code>
     */
    public List<Permissions> fetchByPermit(Byte... values) {
        return fetch(DBnewLogrExtra.tables.Permissions.PERMISSIONS.PERMIT, values);
    }
}
