/*
 * This file is generated by jOOQ.
*/
package DBnewLogrExtra.tables.daos;


import DBnewLogrExtra.tables.pojos.Routes;
import DBnewLogrExtra.tables.records.RoutesRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutesDao extends DAOImpl<RoutesRecord, Routes, Integer> {

    /**
     * Create a new RoutesDao without any configuration
     */
    public RoutesDao() {
        super(DBnewLogrExtra.tables.Routes.ROUTES, Routes.class);
    }

    /**
     * Create a new RoutesDao with an attached configuration
     */
    public RoutesDao(Configuration configuration) {
        super(DBnewLogrExtra.tables.Routes.ROUTES, Routes.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(Routes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<Routes> fetchById(Integer... values) {
        return fetch(DBnewLogrExtra.tables.Routes.ROUTES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Routes fetchOneById(Integer value) {
        return fetchOne(DBnewLogrExtra.tables.Routes.ROUTES.ID, value);
    }

    /**
     * Fetch records that have <code>route IN (values)</code>
     */
    public List<Routes> fetchByRoute(String... values) {
        return fetch(DBnewLogrExtra.tables.Routes.ROUTES.ROUTE, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<Routes> fetchByTitle(String... values) {
        return fetch(DBnewLogrExtra.tables.Routes.ROUTES.TITLE, values);
    }
}
