/*
 * This file is generated by jOOQ.
*/
package DBnewLogrExtra.tables.daos;


import DBnewLogrExtra.tables.pojos.Topics;
import DBnewLogrExtra.tables.records.TopicsRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TopicsDao extends DAOImpl<TopicsRecord, Topics, Integer> {

    /**
     * Create a new TopicsDao without any configuration
     */
    public TopicsDao() {
        super(DBnewLogrExtra.tables.Topics.TOPICS, Topics.class);
    }

    /**
     * Create a new TopicsDao with an attached configuration
     */
    public TopicsDao(Configuration configuration) {
        super(DBnewLogrExtra.tables.Topics.TOPICS, Topics.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(Topics object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<Topics> fetchById(Integer... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Topics fetchOneById(Integer value) {
        return fetchOne(DBnewLogrExtra.tables.Topics.TOPICS.ID, value);
    }

    /**
     * Fetch records that have <code>topic IN (values)</code>
     */
    public List<Topics> fetchByTopic(String... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.TOPIC, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<Topics> fetchByContent(String... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.CONTENT, values);
    }

    /**
     * Fetch records that have <code>slug IN (values)</code>
     */
    public List<Topics> fetchBySlug(String... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.SLUG, values);
    }

    /**
     * Fetch a unique record that has <code>slug = value</code>
     */
    public Topics fetchOneBySlug(String value) {
        return fetchOne(DBnewLogrExtra.tables.Topics.TOPICS.SLUG, value);
    }

    /**
     * Fetch records that have <code>cropic IN (values)</code>
     */
    public List<Topics> fetchByCropic(String... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.CROPIC, values);
    }

    /**
     * Fetch records that have <code>segment IN (values)</code>
     */
    public List<Topics> fetchBySegment(String... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.SEGMENT, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<Topics> fetchByCreated(Timestamp... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.CREATED, values);
    }

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    public List<Topics> fetchByUpdated(Timestamp... values) {
        return fetch(DBnewLogrExtra.tables.Topics.TOPICS.UPDATED, values);
    }
}
