/*
 * This file is generated by jOOQ.
*/
package DBlorg;


import javax.annotation.Generated;

import DBlorg.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>DBlorg</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index QA_ACHIEVEMENTS_USER_ID = Indexes0.QA_ACHIEVEMENTS_USER_ID;
    public static final Index QA_BLOBS_PRIMARY = Indexes0.QA_BLOBS_PRIMARY;
    public static final Index QA_BLOG_COMMENTS_PARENTID = Indexes0.QA_BLOG_COMMENTS_PARENTID;
    public static final Index QA_BLOG_COMMENTS_POSTED = Indexes0.QA_BLOG_COMMENTS_POSTED;
    public static final Index QA_BLOG_COMMENTS_PRIMARY = Indexes0.QA_BLOG_COMMENTS_PRIMARY;
    public static final Index QA_BLOG_COMMENTS_UPDATED = Indexes0.QA_BLOG_COMMENTS_UPDATED;
    public static final Index QA_BLOG_POSTS_POSTED = Indexes0.QA_BLOG_POSTS_POSTED;
    public static final Index QA_BLOG_POSTS_PRIMARY = Indexes0.QA_BLOG_POSTS_PRIMARY;
    public static final Index QA_BLOG_POSTS_UPDATED = Indexes0.QA_BLOG_POSTS_UPDATED;
    public static final Index QA_BLOG_USERS_ACTIVE = Indexes0.QA_BLOG_USERS_ACTIVE;
    public static final Index QA_BLOG_USERS_PRIMARY = Indexes0.QA_BLOG_USERS_PRIMARY;
    public static final Index QA_CACHE_LASTREAD = Indexes0.QA_CACHE_LASTREAD;
    public static final Index QA_CACHE_PRIMARY = Indexes0.QA_CACHE_PRIMARY;
    public static final Index QA_CATEGORIES_BACKPATH = Indexes0.QA_CATEGORIES_BACKPATH;
    public static final Index QA_CATEGORIES_PARENTID = Indexes0.QA_CATEGORIES_PARENTID;
    public static final Index QA_CATEGORIES_PARENTID_2 = Indexes0.QA_CATEGORIES_PARENTID_2;
    public static final Index QA_CATEGORIES_PRIMARY = Indexes0.QA_CATEGORIES_PRIMARY;
    public static final Index QA_CATEGORYMETAS_PRIMARY = Indexes0.QA_CATEGORYMETAS_PRIMARY;
    public static final Index QA_CONTENTWORDS_POSTID = Indexes0.QA_CONTENTWORDS_POSTID;
    public static final Index QA_CONTENTWORDS_WORDID = Indexes0.QA_CONTENTWORDS_WORDID;
    public static final Index QA_COOKIES_PRIMARY = Indexes0.QA_COOKIES_PRIMARY;
    public static final Index QA_IPLIMITS_IP = Indexes0.QA_IPLIMITS_IP;
    public static final Index QA_LOGO_PRIMARY = Indexes0.QA_LOGO_PRIMARY;
    public static final Index QA_MESSAGES_FROMHIDDEN = Indexes0.QA_MESSAGES_FROMHIDDEN;
    public static final Index QA_MESSAGES_PRIMARY = Indexes0.QA_MESSAGES_PRIMARY;
    public static final Index QA_MESSAGES_TOHIDDEN = Indexes0.QA_MESSAGES_TOHIDDEN;
    public static final Index QA_MESSAGES_TOUSERID = Indexes0.QA_MESSAGES_TOUSERID;
    public static final Index QA_MESSAGES_TYPE = Indexes0.QA_MESSAGES_TYPE;
    public static final Index QA_ONLINE_USER_PRIMARY = Indexes0.QA_ONLINE_USER_PRIMARY;
    public static final Index QA_OPTIONS_PRIMARY = Indexes0.QA_OPTIONS_PRIMARY;
    public static final Index QA_PAGES_POSITION = Indexes0.QA_PAGES_POSITION;
    public static final Index QA_PAGES_PRIMARY = Indexes0.QA_PAGES_PRIMARY;
    public static final Index QA_PAGES_TAGS = Indexes0.QA_PAGES_TAGS;
    public static final Index QA_POSTMETAS_PRIMARY = Indexes0.QA_POSTMETAS_PRIMARY;
    public static final Index QA_POSTS_CATEGORYID = Indexes0.QA_POSTS_CATEGORYID;
    public static final Index QA_POSTS_CATEGORYID_2 = Indexes0.QA_POSTS_CATEGORYID_2;
    public static final Index QA_POSTS_CATIDPATH1 = Indexes0.QA_POSTS_CATIDPATH1;
    public static final Index QA_POSTS_CATIDPATH1_2 = Indexes0.QA_POSTS_CATIDPATH1_2;
    public static final Index QA_POSTS_CATIDPATH2 = Indexes0.QA_POSTS_CATIDPATH2;
    public static final Index QA_POSTS_CATIDPATH2_2 = Indexes0.QA_POSTS_CATIDPATH2_2;
    public static final Index QA_POSTS_CATIDPATH3 = Indexes0.QA_POSTS_CATIDPATH3;
    public static final Index QA_POSTS_CATIDPATH3_2 = Indexes0.QA_POSTS_CATIDPATH3_2;
    public static final Index QA_POSTS_CLOSEDBYID = Indexes0.QA_POSTS_CLOSEDBYID;
    public static final Index QA_POSTS_CREATEIP = Indexes0.QA_POSTS_CREATEIP;
    public static final Index QA_POSTS_FLAGCOUNT = Indexes0.QA_POSTS_FLAGCOUNT;
    public static final Index QA_POSTS_IDX_SEARCH = Indexes0.QA_POSTS_IDX_SEARCH;
    public static final Index QA_POSTS_LASTIP = Indexes0.QA_POSTS_LASTIP;
    public static final Index QA_POSTS_LASTUSERID = Indexes0.QA_POSTS_LASTUSERID;
    public static final Index QA_POSTS_PARENTID = Indexes0.QA_POSTS_PARENTID;
    public static final Index QA_POSTS_PRIMARY = Indexes0.QA_POSTS_PRIMARY;
    public static final Index QA_POSTS_SELCHILDID = Indexes0.QA_POSTS_SELCHILDID;
    public static final Index QA_POSTS_TYPE = Indexes0.QA_POSTS_TYPE;
    public static final Index QA_POSTS_TYPE_2 = Indexes0.QA_POSTS_TYPE_2;
    public static final Index QA_POSTS_TYPE_4 = Indexes0.QA_POSTS_TYPE_4;
    public static final Index QA_POSTS_TYPE_5 = Indexes0.QA_POSTS_TYPE_5;
    public static final Index QA_POSTS_TYPE_6 = Indexes0.QA_POSTS_TYPE_6;
    public static final Index QA_POSTS_TYPE_7 = Indexes0.QA_POSTS_TYPE_7;
    public static final Index QA_POSTS_UPDATED = Indexes0.QA_POSTS_UPDATED;
    public static final Index QA_POSTS_USERID = Indexes0.QA_POSTS_USERID;
    public static final Index QA_POSTTAGS_POSTID = Indexes0.QA_POSTTAGS_POSTID;
    public static final Index QA_POSTTAGS_WORDID = Indexes0.QA_POSTTAGS_WORDID;
    public static final Index QA_SHAREDEVENTS_ENTITYTYPE = Indexes0.QA_SHAREDEVENTS_ENTITYTYPE;
    public static final Index QA_SHAREDEVENTS_QUESTIONID = Indexes0.QA_SHAREDEVENTS_QUESTIONID;
    public static final Index QA_TAGMETAS_PRIMARY = Indexes0.QA_TAGMETAS_PRIMARY;
    public static final Index QA_TAGWORDS_POSTID = Indexes0.QA_TAGWORDS_POSTID;
    public static final Index QA_TAGWORDS_WORDID = Indexes0.QA_TAGWORDS_WORDID;
    public static final Index QA_TITLEWORDS_POSTID = Indexes0.QA_TITLEWORDS_POSTID;
    public static final Index QA_TITLEWORDS_WORDID = Indexes0.QA_TITLEWORDS_WORDID;
    public static final Index QA_TOPICS_PRIMARY = Indexes0.QA_TOPICS_PRIMARY;
    public static final Index QA_USERBADGES_PRIMARY = Indexes0.QA_USERBADGES_PRIMARY;
    public static final Index QA_USEREVENTS_QUESTIONID = Indexes0.QA_USEREVENTS_QUESTIONID;
    public static final Index QA_USEREVENTS_USERID = Indexes0.QA_USEREVENTS_USERID;
    public static final Index QA_USERFAVORITES_ENTITYTYPE = Indexes0.QA_USERFAVORITES_ENTITYTYPE;
    public static final Index QA_USERFAVORITES_PRIMARY = Indexes0.QA_USERFAVORITES_PRIMARY;
    public static final Index QA_USERFAVORITES_USERID = Indexes0.QA_USERFAVORITES_USERID;
    public static final Index QA_USERFIELDS_PRIMARY = Indexes0.QA_USERFIELDS_PRIMARY;
    public static final Index QA_USERLEVELS_ENTITYTYPE = Indexes0.QA_USERLEVELS_ENTITYTYPE;
    public static final Index QA_USERLEVELS_USERID = Indexes0.QA_USERLEVELS_USERID;
    public static final Index QA_USERLIMITS_USERID = Indexes0.QA_USERLIMITS_USERID;
    public static final Index QA_USERLOGINS_SOURCE = Indexes0.QA_USERLOGINS_SOURCE;
    public static final Index QA_USERLOGINS_USERID = Indexes0.QA_USERLOGINS_USERID;
    public static final Index QA_USERMETAS_PRIMARY = Indexes0.QA_USERMETAS_PRIMARY;
    public static final Index QA_USERNOTICES_PRIMARY = Indexes0.QA_USERNOTICES_PRIMARY;
    public static final Index QA_USERNOTICES_USERID = Indexes0.QA_USERNOTICES_USERID;
    public static final Index QA_USERPOINTS_POINTS = Indexes0.QA_USERPOINTS_POINTS;
    public static final Index QA_USERPOINTS_PRIMARY = Indexes0.QA_USERPOINTS_PRIMARY;
    public static final Index QA_USERPROFILE_USERID = Indexes0.QA_USERPROFILE_USERID;
    public static final Index QA_USERS_CREATED = Indexes0.QA_USERS_CREATED;
    public static final Index QA_USERS_EMAIL = Indexes0.QA_USERS_EMAIL;
    public static final Index QA_USERS_HANDLE = Indexes0.QA_USERS_HANDLE;
    public static final Index QA_USERS_LEVEL = Indexes0.QA_USERS_LEVEL;
    public static final Index QA_USERS_PRIMARY = Indexes0.QA_USERS_PRIMARY;
    public static final Index QA_USERVOTES_POSTID = Indexes0.QA_USERVOTES_POSTID;
    public static final Index QA_USERVOTES_USERID = Indexes0.QA_USERVOTES_USERID;
    public static final Index QA_WIDGETS_POSITION = Indexes0.QA_WIDGETS_POSITION;
    public static final Index QA_WIDGETS_PRIMARY = Indexes0.QA_WIDGETS_PRIMARY;
    public static final Index QA_WORDS_PRIMARY = Indexes0.QA_WORDS_PRIMARY;
    public static final Index QA_WORDS_TAGCOUNT = Indexes0.QA_WORDS_TAGCOUNT;
    public static final Index QA_WORDS_WORD = Indexes0.QA_WORDS_WORD;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index QA_ACHIEVEMENTS_USER_ID = createIndex("user_id", QaAchievements.QA_ACHIEVEMENTS, new OrderField[] { QaAchievements.QA_ACHIEVEMENTS.USER_ID }, true);
        public static Index QA_BLOBS_PRIMARY = createIndex("PRIMARY", QaBlobs.QA_BLOBS, new OrderField[] { QaBlobs.QA_BLOBS.BLOBID }, true);
        public static Index QA_BLOG_COMMENTS_PARENTID = createIndex("parentid", QaBlogComments.QA_BLOG_COMMENTS, new OrderField[] { QaBlogComments.QA_BLOG_COMMENTS.PARENTID }, false);
        public static Index QA_BLOG_COMMENTS_POSTED = createIndex("posted", QaBlogComments.QA_BLOG_COMMENTS, new OrderField[] { QaBlogComments.QA_BLOG_COMMENTS.POSTED }, false);
        public static Index QA_BLOG_COMMENTS_PRIMARY = createIndex("PRIMARY", QaBlogComments.QA_BLOG_COMMENTS, new OrderField[] { QaBlogComments.QA_BLOG_COMMENTS.POSTID }, true);
        public static Index QA_BLOG_COMMENTS_UPDATED = createIndex("updated", QaBlogComments.QA_BLOG_COMMENTS, new OrderField[] { QaBlogComments.QA_BLOG_COMMENTS.UPDATED }, false);
        public static Index QA_BLOG_POSTS_POSTED = createIndex("posted", QaBlogPosts.QA_BLOG_POSTS, new OrderField[] { QaBlogPosts.QA_BLOG_POSTS.POSTED }, false);
        public static Index QA_BLOG_POSTS_PRIMARY = createIndex("PRIMARY", QaBlogPosts.QA_BLOG_POSTS, new OrderField[] { QaBlogPosts.QA_BLOG_POSTS.POSTID }, true);
        public static Index QA_BLOG_POSTS_UPDATED = createIndex("updated", QaBlogPosts.QA_BLOG_POSTS, new OrderField[] { QaBlogPosts.QA_BLOG_POSTS.UPDATED }, false);
        public static Index QA_BLOG_USERS_ACTIVE = createIndex("active", QaBlogUsers.QA_BLOG_USERS, new OrderField[] { QaBlogUsers.QA_BLOG_USERS.LASTPOLLED }, false);
        public static Index QA_BLOG_USERS_PRIMARY = createIndex("PRIMARY", QaBlogUsers.QA_BLOG_USERS, new OrderField[] { QaBlogUsers.QA_BLOG_USERS.USERID }, true);
        public static Index QA_CACHE_LASTREAD = createIndex("lastread", QaCache.QA_CACHE, new OrderField[] { QaCache.QA_CACHE.LASTREAD }, false);
        public static Index QA_CACHE_PRIMARY = createIndex("PRIMARY", QaCache.QA_CACHE, new OrderField[] { QaCache.QA_CACHE.TYPE, QaCache.QA_CACHE.CACHEID }, true);
        public static Index QA_CATEGORIES_BACKPATH = createIndex("backpath", QaCategories.QA_CATEGORIES, new OrderField[] { QaCategories.QA_CATEGORIES.BACKPATH }, false);
        public static Index QA_CATEGORIES_PARENTID = createIndex("parentid", QaCategories.QA_CATEGORIES, new OrderField[] { QaCategories.QA_CATEGORIES.PARENTID, QaCategories.QA_CATEGORIES.TAGS }, true);
        public static Index QA_CATEGORIES_PARENTID_2 = createIndex("parentid_2", QaCategories.QA_CATEGORIES, new OrderField[] { QaCategories.QA_CATEGORIES.PARENTID, QaCategories.QA_CATEGORIES.POSITION }, true);
        public static Index QA_CATEGORIES_PRIMARY = createIndex("PRIMARY", QaCategories.QA_CATEGORIES, new OrderField[] { QaCategories.QA_CATEGORIES.CATEGORYID }, true);
        public static Index QA_CATEGORYMETAS_PRIMARY = createIndex("PRIMARY", QaCategorymetas.QA_CATEGORYMETAS, new OrderField[] { QaCategorymetas.QA_CATEGORYMETAS.CATEGORYID, QaCategorymetas.QA_CATEGORYMETAS.TITLE }, true);
        public static Index QA_CONTENTWORDS_POSTID = createIndex("postid", QaContentwords.QA_CONTENTWORDS, new OrderField[] { QaContentwords.QA_CONTENTWORDS.POSTID }, false);
        public static Index QA_CONTENTWORDS_WORDID = createIndex("wordid", QaContentwords.QA_CONTENTWORDS, new OrderField[] { QaContentwords.QA_CONTENTWORDS.WORDID }, false);
        public static Index QA_COOKIES_PRIMARY = createIndex("PRIMARY", QaCookies.QA_COOKIES, new OrderField[] { QaCookies.QA_COOKIES.COOKIEID }, true);
        public static Index QA_IPLIMITS_IP = createIndex("ip", QaIplimits.QA_IPLIMITS, new OrderField[] { QaIplimits.QA_IPLIMITS.IP, QaIplimits.QA_IPLIMITS.ACTION }, true);
        public static Index QA_LOGO_PRIMARY = createIndex("PRIMARY", QaLogo.QA_LOGO, new OrderField[] { QaLogo.QA_LOGO.ID }, true);
        public static Index QA_MESSAGES_FROMHIDDEN = createIndex("fromhidden", QaMessages.QA_MESSAGES, new OrderField[] { QaMessages.QA_MESSAGES.FROMHIDDEN }, false);
        public static Index QA_MESSAGES_PRIMARY = createIndex("PRIMARY", QaMessages.QA_MESSAGES, new OrderField[] { QaMessages.QA_MESSAGES.MESSAGEID }, true);
        public static Index QA_MESSAGES_TOHIDDEN = createIndex("tohidden", QaMessages.QA_MESSAGES, new OrderField[] { QaMessages.QA_MESSAGES.TOHIDDEN }, false);
        public static Index QA_MESSAGES_TOUSERID = createIndex("touserid", QaMessages.QA_MESSAGES, new OrderField[] { QaMessages.QA_MESSAGES.TOUSERID, QaMessages.QA_MESSAGES.TYPE, QaMessages.QA_MESSAGES.CREATED }, false);
        public static Index QA_MESSAGES_TYPE = createIndex("type", QaMessages.QA_MESSAGES, new OrderField[] { QaMessages.QA_MESSAGES.TYPE, QaMessages.QA_MESSAGES.FROMUSERID, QaMessages.QA_MESSAGES.TOUSERID, QaMessages.QA_MESSAGES.CREATED }, false);
        public static Index QA_ONLINE_USER_PRIMARY = createIndex("PRIMARY", QaOnlineUser.QA_ONLINE_USER, new OrderField[] { QaOnlineUser.QA_ONLINE_USER.ID }, true);
        public static Index QA_OPTIONS_PRIMARY = createIndex("PRIMARY", QaOptions.QA_OPTIONS, new OrderField[] { QaOptions.QA_OPTIONS.TITLE }, true);
        public static Index QA_PAGES_POSITION = createIndex("position", QaPages.QA_PAGES, new OrderField[] { QaPages.QA_PAGES.POSITION }, true);
        public static Index QA_PAGES_PRIMARY = createIndex("PRIMARY", QaPages.QA_PAGES, new OrderField[] { QaPages.QA_PAGES.PAGEID }, true);
        public static Index QA_PAGES_TAGS = createIndex("tags", QaPages.QA_PAGES, new OrderField[] { QaPages.QA_PAGES.TAGS }, false);
        public static Index QA_POSTMETAS_PRIMARY = createIndex("PRIMARY", QaPostmetas.QA_POSTMETAS, new OrderField[] { QaPostmetas.QA_POSTMETAS.POSTID, QaPostmetas.QA_POSTMETAS.TITLE }, true);
        public static Index QA_POSTS_CATEGORYID = createIndex("categoryid", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATEGORYID, QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_CATEGORYID_2 = createIndex("categoryid_2", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATEGORYID, QaPosts.QA_POSTS.UPDATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_CATIDPATH1 = createIndex("catidpath1", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATIDPATH1, QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_CATIDPATH1_2 = createIndex("catidpath1_2", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATIDPATH1, QaPosts.QA_POSTS.UPDATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_CATIDPATH2 = createIndex("catidpath2", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATIDPATH2, QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_CATIDPATH2_2 = createIndex("catidpath2_2", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATIDPATH2, QaPosts.QA_POSTS.UPDATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_CATIDPATH3 = createIndex("catidpath3", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATIDPATH3, QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_CATIDPATH3_2 = createIndex("catidpath3_2", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CATIDPATH3, QaPosts.QA_POSTS.UPDATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_CLOSEDBYID = createIndex("closedbyid", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CLOSEDBYID }, false);
        public static Index QA_POSTS_CREATEIP = createIndex("createip", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.CREATEIP, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_FLAGCOUNT = createIndex("flagcount", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.FLAGCOUNT, QaPosts.QA_POSTS.CREATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_IDX_SEARCH = createIndex("idx_search", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.TITLE, QaPosts.QA_POSTS.CONTENT }, false);
        public static Index QA_POSTS_LASTIP = createIndex("lastip", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.LASTIP, QaPosts.QA_POSTS.UPDATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_LASTUSERID = createIndex("lastuserid", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.LASTUSERID, QaPosts.QA_POSTS.UPDATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_PARENTID = createIndex("parentid", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.PARENTID, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_PRIMARY = createIndex("PRIMARY", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.POSTID }, true);
        public static Index QA_POSTS_SELCHILDID = createIndex("selchildid", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.SELCHILDID, QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_TYPE = createIndex("type", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_TYPE_2 = createIndex("type_2", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.ACOUNT, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_TYPE_4 = createIndex("type_4", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.NETVOTES, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_TYPE_5 = createIndex("type_5", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.VIEWS, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_TYPE_6 = createIndex("type_6", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.HOTNESS }, false);
        public static Index QA_POSTS_TYPE_7 = createIndex("type_7", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.AMAXVOTE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTS_UPDATED = createIndex("updated", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.UPDATED, QaPosts.QA_POSTS.TYPE }, false);
        public static Index QA_POSTS_USERID = createIndex("userid", QaPosts.QA_POSTS, new OrderField[] { QaPosts.QA_POSTS.USERID, QaPosts.QA_POSTS.TYPE, QaPosts.QA_POSTS.CREATED }, false);
        public static Index QA_POSTTAGS_POSTID = createIndex("postid", QaPosttags.QA_POSTTAGS, new OrderField[] { QaPosttags.QA_POSTTAGS.POSTID }, false);
        public static Index QA_POSTTAGS_WORDID = createIndex("wordid", QaPosttags.QA_POSTTAGS, new OrderField[] { QaPosttags.QA_POSTTAGS.WORDID, QaPosttags.QA_POSTTAGS.POSTCREATED }, false);
        public static Index QA_SHAREDEVENTS_ENTITYTYPE = createIndex("entitytype", QaSharedevents.QA_SHAREDEVENTS, new OrderField[] { QaSharedevents.QA_SHAREDEVENTS.ENTITYTYPE, QaSharedevents.QA_SHAREDEVENTS.ENTITYID, QaSharedevents.QA_SHAREDEVENTS.UPDATED }, false);
        public static Index QA_SHAREDEVENTS_QUESTIONID = createIndex("questionid", QaSharedevents.QA_SHAREDEVENTS, new OrderField[] { QaSharedevents.QA_SHAREDEVENTS.QUESTIONID, QaSharedevents.QA_SHAREDEVENTS.ENTITYTYPE, QaSharedevents.QA_SHAREDEVENTS.ENTITYID }, false);
        public static Index QA_TAGMETAS_PRIMARY = createIndex("PRIMARY", QaTagmetas.QA_TAGMETAS, new OrderField[] { QaTagmetas.QA_TAGMETAS.TAG, QaTagmetas.QA_TAGMETAS.TITLE }, true);
        public static Index QA_TAGWORDS_POSTID = createIndex("postid", QaTagwords.QA_TAGWORDS, new OrderField[] { QaTagwords.QA_TAGWORDS.POSTID }, false);
        public static Index QA_TAGWORDS_WORDID = createIndex("wordid", QaTagwords.QA_TAGWORDS, new OrderField[] { QaTagwords.QA_TAGWORDS.WORDID }, false);
        public static Index QA_TITLEWORDS_POSTID = createIndex("postid", QaTitlewords.QA_TITLEWORDS, new OrderField[] { QaTitlewords.QA_TITLEWORDS.POSTID }, false);
        public static Index QA_TITLEWORDS_WORDID = createIndex("wordid", QaTitlewords.QA_TITLEWORDS, new OrderField[] { QaTitlewords.QA_TITLEWORDS.WORDID }, false);
        public static Index QA_TOPICS_PRIMARY = createIndex("PRIMARY", QaTopics.QA_TOPICS, new OrderField[] { QaTopics.QA_TOPICS.ID }, true);
        public static Index QA_USERBADGES_PRIMARY = createIndex("PRIMARY", QaUserbadges.QA_USERBADGES, new OrderField[] { QaUserbadges.QA_USERBADGES.ID }, true);
        public static Index QA_USEREVENTS_QUESTIONID = createIndex("questionid", QaUserevents.QA_USEREVENTS, new OrderField[] { QaUserevents.QA_USEREVENTS.QUESTIONID, QaUserevents.QA_USEREVENTS.USERID }, false);
        public static Index QA_USEREVENTS_USERID = createIndex("userid", QaUserevents.QA_USEREVENTS, new OrderField[] { QaUserevents.QA_USEREVENTS.USERID, QaUserevents.QA_USEREVENTS.UPDATED }, false);
        public static Index QA_USERFAVORITES_ENTITYTYPE = createIndex("entitytype", QaUserfavorites.QA_USERFAVORITES, new OrderField[] { QaUserfavorites.QA_USERFAVORITES.ENTITYTYPE, QaUserfavorites.QA_USERFAVORITES.ENTITYID, QaUserfavorites.QA_USERFAVORITES.NOUSEREVENTS }, false);
        public static Index QA_USERFAVORITES_PRIMARY = createIndex("PRIMARY", QaUserfavorites.QA_USERFAVORITES, new OrderField[] { QaUserfavorites.QA_USERFAVORITES.USERID, QaUserfavorites.QA_USERFAVORITES.ENTITYTYPE, QaUserfavorites.QA_USERFAVORITES.ENTITYID }, true);
        public static Index QA_USERFAVORITES_USERID = createIndex("userid", QaUserfavorites.QA_USERFAVORITES, new OrderField[] { QaUserfavorites.QA_USERFAVORITES.USERID, QaUserfavorites.QA_USERFAVORITES.NOUSEREVENTS }, false);
        public static Index QA_USERFIELDS_PRIMARY = createIndex("PRIMARY", QaUserfields.QA_USERFIELDS, new OrderField[] { QaUserfields.QA_USERFIELDS.FIELDID }, true);
        public static Index QA_USERLEVELS_ENTITYTYPE = createIndex("entitytype", QaUserlevels.QA_USERLEVELS, new OrderField[] { QaUserlevels.QA_USERLEVELS.ENTITYTYPE, QaUserlevels.QA_USERLEVELS.ENTITYID }, false);
        public static Index QA_USERLEVELS_USERID = createIndex("userid", QaUserlevels.QA_USERLEVELS, new OrderField[] { QaUserlevels.QA_USERLEVELS.USERID, QaUserlevels.QA_USERLEVELS.ENTITYTYPE, QaUserlevels.QA_USERLEVELS.ENTITYID }, true);
        public static Index QA_USERLIMITS_USERID = createIndex("userid", QaUserlimits.QA_USERLIMITS, new OrderField[] { QaUserlimits.QA_USERLIMITS.USERID, QaUserlimits.QA_USERLIMITS.ACTION }, true);
        public static Index QA_USERLOGINS_SOURCE = createIndex("source", QaUserlogins.QA_USERLOGINS, new OrderField[] { QaUserlogins.QA_USERLOGINS.SOURCE, QaUserlogins.QA_USERLOGINS.IDENTIFIERMD5 }, false);
        public static Index QA_USERLOGINS_USERID = createIndex("userid", QaUserlogins.QA_USERLOGINS, new OrderField[] { QaUserlogins.QA_USERLOGINS.USERID }, false);
        public static Index QA_USERMETAS_PRIMARY = createIndex("PRIMARY", QaUsermetas.QA_USERMETAS, new OrderField[] { QaUsermetas.QA_USERMETAS.USERID, QaUsermetas.QA_USERMETAS.TITLE }, true);
        public static Index QA_USERNOTICES_PRIMARY = createIndex("PRIMARY", QaUsernotices.QA_USERNOTICES, new OrderField[] { QaUsernotices.QA_USERNOTICES.NOTICEID }, true);
        public static Index QA_USERNOTICES_USERID = createIndex("userid", QaUsernotices.QA_USERNOTICES, new OrderField[] { QaUsernotices.QA_USERNOTICES.USERID, QaUsernotices.QA_USERNOTICES.CREATED }, false);
        public static Index QA_USERPOINTS_POINTS = createIndex("points", QaUserpoints.QA_USERPOINTS, new OrderField[] { QaUserpoints.QA_USERPOINTS.POINTS }, false);
        public static Index QA_USERPOINTS_PRIMARY = createIndex("PRIMARY", QaUserpoints.QA_USERPOINTS, new OrderField[] { QaUserpoints.QA_USERPOINTS.USERID }, true);
        public static Index QA_USERPROFILE_USERID = createIndex("userid", QaUserprofile.QA_USERPROFILE, new OrderField[] { QaUserprofile.QA_USERPROFILE.USERID, QaUserprofile.QA_USERPROFILE.TITLE }, true);
        public static Index QA_USERS_CREATED = createIndex("created", QaUsers.QA_USERS, new OrderField[] { QaUsers.QA_USERS.CREATED, QaUsers.QA_USERS.LEVEL, QaUsers.QA_USERS.FLAGS }, false);
        public static Index QA_USERS_EMAIL = createIndex("email", QaUsers.QA_USERS, new OrderField[] { QaUsers.QA_USERS.EMAIL }, false);
        public static Index QA_USERS_HANDLE = createIndex("handle", QaUsers.QA_USERS, new OrderField[] { QaUsers.QA_USERS.HANDLE }, false);
        public static Index QA_USERS_LEVEL = createIndex("level", QaUsers.QA_USERS, new OrderField[] { QaUsers.QA_USERS.LEVEL }, false);
        public static Index QA_USERS_PRIMARY = createIndex("PRIMARY", QaUsers.QA_USERS, new OrderField[] { QaUsers.QA_USERS.USERID }, true);
        public static Index QA_USERVOTES_POSTID = createIndex("postid", QaUservotes.QA_USERVOTES, new OrderField[] { QaUservotes.QA_USERVOTES.POSTID }, false);
        public static Index QA_USERVOTES_USERID = createIndex("userid", QaUservotes.QA_USERVOTES, new OrderField[] { QaUservotes.QA_USERVOTES.USERID, QaUservotes.QA_USERVOTES.POSTID }, true);
        public static Index QA_WIDGETS_POSITION = createIndex("position", QaWidgets.QA_WIDGETS, new OrderField[] { QaWidgets.QA_WIDGETS.POSITION }, true);
        public static Index QA_WIDGETS_PRIMARY = createIndex("PRIMARY", QaWidgets.QA_WIDGETS, new OrderField[] { QaWidgets.QA_WIDGETS.WIDGETID }, true);
        public static Index QA_WORDS_PRIMARY = createIndex("PRIMARY", QaWords.QA_WORDS, new OrderField[] { QaWords.QA_WORDS.WORDID }, true);
        public static Index QA_WORDS_TAGCOUNT = createIndex("tagcount", QaWords.QA_WORDS, new OrderField[] { QaWords.QA_WORDS.TAGCOUNT }, false);
        public static Index QA_WORDS_WORD = createIndex("word", QaWords.QA_WORDS, new OrderField[] { QaWords.QA_WORDS.WORD }, false);
    }
}
