/*
 * This file is generated by jOOQ.
*/
package DBlorg;


import javax.annotation.Generated;

import DBlorg.tables.*;
import DBlorg.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>DBlorg</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<QaBlogCommentsRecord, UInteger> IDENTITY_QA_BLOG_COMMENTS = Identities0.IDENTITY_QA_BLOG_COMMENTS;
    public static final Identity<QaBlogPostsRecord, UInteger> IDENTITY_QA_BLOG_POSTS = Identities0.IDENTITY_QA_BLOG_POSTS;
    public static final Identity<QaCategoriesRecord, UInteger> IDENTITY_QA_CATEGORIES = Identities0.IDENTITY_QA_CATEGORIES;
    public static final Identity<QaLogoRecord, Integer> IDENTITY_QA_LOGO = Identities0.IDENTITY_QA_LOGO;
    public static final Identity<QaMessagesRecord, UInteger> IDENTITY_QA_MESSAGES = Identities0.IDENTITY_QA_MESSAGES;
    public static final Identity<QaOnlineUserRecord, Integer> IDENTITY_QA_ONLINE_USER = Identities0.IDENTITY_QA_ONLINE_USER;
    public static final Identity<QaPagesRecord, UShort> IDENTITY_QA_PAGES = Identities0.IDENTITY_QA_PAGES;
    public static final Identity<QaPostsRecord, UInteger> IDENTITY_QA_POSTS = Identities0.IDENTITY_QA_POSTS;
    public static final Identity<QaTopicsRecord, Integer> IDENTITY_QA_TOPICS = Identities0.IDENTITY_QA_TOPICS;
    public static final Identity<QaUserbadgesRecord, Integer> IDENTITY_QA_USERBADGES = Identities0.IDENTITY_QA_USERBADGES;
    public static final Identity<QaUserfieldsRecord, UShort> IDENTITY_QA_USERFIELDS = Identities0.IDENTITY_QA_USERFIELDS;
    public static final Identity<QaUsernoticesRecord, UInteger> IDENTITY_QA_USERNOTICES = Identities0.IDENTITY_QA_USERNOTICES;
    public static final Identity<QaUsersRecord, UInteger> IDENTITY_QA_USERS = Identities0.IDENTITY_QA_USERS;
    public static final Identity<QaWidgetsRecord, UShort> IDENTITY_QA_WIDGETS = Identities0.IDENTITY_QA_WIDGETS;
    public static final Identity<QaWordsRecord, UInteger> IDENTITY_QA_WORDS = Identities0.IDENTITY_QA_WORDS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<QaAchievementsRecord> KEY_QA_ACHIEVEMENTS_USER_ID = UniqueKeys0.KEY_QA_ACHIEVEMENTS_USER_ID;
    public static final UniqueKey<QaBlobsRecord> KEY_QA_BLOBS_PRIMARY = UniqueKeys0.KEY_QA_BLOBS_PRIMARY;
    public static final UniqueKey<QaBlogCommentsRecord> KEY_QA_BLOG_COMMENTS_PRIMARY = UniqueKeys0.KEY_QA_BLOG_COMMENTS_PRIMARY;
    public static final UniqueKey<QaBlogPostsRecord> KEY_QA_BLOG_POSTS_PRIMARY = UniqueKeys0.KEY_QA_BLOG_POSTS_PRIMARY;
    public static final UniqueKey<QaBlogUsersRecord> KEY_QA_BLOG_USERS_PRIMARY = UniqueKeys0.KEY_QA_BLOG_USERS_PRIMARY;
    public static final UniqueKey<QaCacheRecord> KEY_QA_CACHE_PRIMARY = UniqueKeys0.KEY_QA_CACHE_PRIMARY;
    public static final UniqueKey<QaCategoriesRecord> KEY_QA_CATEGORIES_PRIMARY = UniqueKeys0.KEY_QA_CATEGORIES_PRIMARY;
    public static final UniqueKey<QaCategoriesRecord> KEY_QA_CATEGORIES_PARENTID = UniqueKeys0.KEY_QA_CATEGORIES_PARENTID;
    public static final UniqueKey<QaCategoriesRecord> KEY_QA_CATEGORIES_PARENTID_2 = UniqueKeys0.KEY_QA_CATEGORIES_PARENTID_2;
    public static final UniqueKey<QaCategorymetasRecord> KEY_QA_CATEGORYMETAS_PRIMARY = UniqueKeys0.KEY_QA_CATEGORYMETAS_PRIMARY;
    public static final UniqueKey<QaCookiesRecord> KEY_QA_COOKIES_PRIMARY = UniqueKeys0.KEY_QA_COOKIES_PRIMARY;
    public static final UniqueKey<QaIplimitsRecord> KEY_QA_IPLIMITS_IP = UniqueKeys0.KEY_QA_IPLIMITS_IP;
    public static final UniqueKey<QaLogoRecord> KEY_QA_LOGO_PRIMARY = UniqueKeys0.KEY_QA_LOGO_PRIMARY;
    public static final UniqueKey<QaMessagesRecord> KEY_QA_MESSAGES_PRIMARY = UniqueKeys0.KEY_QA_MESSAGES_PRIMARY;
    public static final UniqueKey<QaOnlineUserRecord> KEY_QA_ONLINE_USER_PRIMARY = UniqueKeys0.KEY_QA_ONLINE_USER_PRIMARY;
    public static final UniqueKey<QaOptionsRecord> KEY_QA_OPTIONS_PRIMARY = UniqueKeys0.KEY_QA_OPTIONS_PRIMARY;
    public static final UniqueKey<QaPagesRecord> KEY_QA_PAGES_PRIMARY = UniqueKeys0.KEY_QA_PAGES_PRIMARY;
    public static final UniqueKey<QaPagesRecord> KEY_QA_PAGES_POSITION = UniqueKeys0.KEY_QA_PAGES_POSITION;
    public static final UniqueKey<QaPostmetasRecord> KEY_QA_POSTMETAS_PRIMARY = UniqueKeys0.KEY_QA_POSTMETAS_PRIMARY;
    public static final UniqueKey<QaPostsRecord> KEY_QA_POSTS_PRIMARY = UniqueKeys0.KEY_QA_POSTS_PRIMARY;
    public static final UniqueKey<QaTagmetasRecord> KEY_QA_TAGMETAS_PRIMARY = UniqueKeys0.KEY_QA_TAGMETAS_PRIMARY;
    public static final UniqueKey<QaTopicsRecord> KEY_QA_TOPICS_PRIMARY = UniqueKeys0.KEY_QA_TOPICS_PRIMARY;
    public static final UniqueKey<QaUserbadgesRecord> KEY_QA_USERBADGES_PRIMARY = UniqueKeys0.KEY_QA_USERBADGES_PRIMARY;
    public static final UniqueKey<QaUserfavoritesRecord> KEY_QA_USERFAVORITES_PRIMARY = UniqueKeys0.KEY_QA_USERFAVORITES_PRIMARY;
    public static final UniqueKey<QaUserfieldsRecord> KEY_QA_USERFIELDS_PRIMARY = UniqueKeys0.KEY_QA_USERFIELDS_PRIMARY;
    public static final UniqueKey<QaUserlevelsRecord> KEY_QA_USERLEVELS_USERID = UniqueKeys0.KEY_QA_USERLEVELS_USERID;
    public static final UniqueKey<QaUserlimitsRecord> KEY_QA_USERLIMITS_USERID = UniqueKeys0.KEY_QA_USERLIMITS_USERID;
    public static final UniqueKey<QaUsermetasRecord> KEY_QA_USERMETAS_PRIMARY = UniqueKeys0.KEY_QA_USERMETAS_PRIMARY;
    public static final UniqueKey<QaUsernoticesRecord> KEY_QA_USERNOTICES_PRIMARY = UniqueKeys0.KEY_QA_USERNOTICES_PRIMARY;
    public static final UniqueKey<QaUserpointsRecord> KEY_QA_USERPOINTS_PRIMARY = UniqueKeys0.KEY_QA_USERPOINTS_PRIMARY;
    public static final UniqueKey<QaUserprofileRecord> KEY_QA_USERPROFILE_USERID = UniqueKeys0.KEY_QA_USERPROFILE_USERID;
    public static final UniqueKey<QaUsersRecord> KEY_QA_USERS_PRIMARY = UniqueKeys0.KEY_QA_USERS_PRIMARY;
    public static final UniqueKey<QaUservotesRecord> KEY_QA_USERVOTES_USERID = UniqueKeys0.KEY_QA_USERVOTES_USERID;
    public static final UniqueKey<QaWidgetsRecord> KEY_QA_WIDGETS_PRIMARY = UniqueKeys0.KEY_QA_WIDGETS_PRIMARY;
    public static final UniqueKey<QaWidgetsRecord> KEY_QA_WIDGETS_POSITION = UniqueKeys0.KEY_QA_WIDGETS_POSITION;
    public static final UniqueKey<QaWordsRecord> KEY_QA_WORDS_PRIMARY = UniqueKeys0.KEY_QA_WORDS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<QaCategorymetasRecord, QaCategoriesRecord> QA_CATEGORYMETAS_IBFK_1 = ForeignKeys0.QA_CATEGORYMETAS_IBFK_1;
    public static final ForeignKey<QaContentwordsRecord, QaPostsRecord> QA_CONTENTWORDS_IBFK_1 = ForeignKeys0.QA_CONTENTWORDS_IBFK_1;
    public static final ForeignKey<QaContentwordsRecord, QaWordsRecord> QA_CONTENTWORDS_IBFK_2 = ForeignKeys0.QA_CONTENTWORDS_IBFK_2;
    public static final ForeignKey<QaPostmetasRecord, QaPostsRecord> QA_POSTMETAS_IBFK_1 = ForeignKeys0.QA_POSTMETAS_IBFK_1;
    public static final ForeignKey<QaPostsRecord, QaPostsRecord> QA_POSTS_IBFK_2 = ForeignKeys0.QA_POSTS_IBFK_2;
    public static final ForeignKey<QaPostsRecord, QaCategoriesRecord> QA_POSTS_IBFK_3 = ForeignKeys0.QA_POSTS_IBFK_3;
    public static final ForeignKey<QaPostsRecord, QaPostsRecord> QA_POSTS_IBFK_4 = ForeignKeys0.QA_POSTS_IBFK_4;
    public static final ForeignKey<QaPosttagsRecord, QaPostsRecord> QA_POSTTAGS_IBFK_1 = ForeignKeys0.QA_POSTTAGS_IBFK_1;
    public static final ForeignKey<QaPosttagsRecord, QaWordsRecord> QA_POSTTAGS_IBFK_2 = ForeignKeys0.QA_POSTTAGS_IBFK_2;
    public static final ForeignKey<QaTagwordsRecord, QaPostsRecord> QA_TAGWORDS_IBFK_1 = ForeignKeys0.QA_TAGWORDS_IBFK_1;
    public static final ForeignKey<QaTagwordsRecord, QaWordsRecord> QA_TAGWORDS_IBFK_2 = ForeignKeys0.QA_TAGWORDS_IBFK_2;
    public static final ForeignKey<QaTitlewordsRecord, QaPostsRecord> QA_TITLEWORDS_IBFK_1 = ForeignKeys0.QA_TITLEWORDS_IBFK_1;
    public static final ForeignKey<QaTitlewordsRecord, QaWordsRecord> QA_TITLEWORDS_IBFK_2 = ForeignKeys0.QA_TITLEWORDS_IBFK_2;
    public static final ForeignKey<QaUserloginsRecord, QaUsersRecord> QA_USERLOGINS_IBFK_1 = ForeignKeys0.QA_USERLOGINS_IBFK_1;
    public static final ForeignKey<QaUserprofileRecord, QaUsersRecord> QA_USERPROFILE_IBFK_1 = ForeignKeys0.QA_USERPROFILE_IBFK_1;
    public static final ForeignKey<QaUservotesRecord, QaPostsRecord> QA_USERVOTES_IBFK_1 = ForeignKeys0.QA_USERVOTES_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<QaBlogCommentsRecord, UInteger> IDENTITY_QA_BLOG_COMMENTS = createIdentity(QaBlogComments.QA_BLOG_COMMENTS, QaBlogComments.QA_BLOG_COMMENTS.POSTID);
        public static Identity<QaBlogPostsRecord, UInteger> IDENTITY_QA_BLOG_POSTS = createIdentity(QaBlogPosts.QA_BLOG_POSTS, QaBlogPosts.QA_BLOG_POSTS.POSTID);
        public static Identity<QaCategoriesRecord, UInteger> IDENTITY_QA_CATEGORIES = createIdentity(QaCategories.QA_CATEGORIES, QaCategories.QA_CATEGORIES.CATEGORYID);
        public static Identity<QaLogoRecord, Integer> IDENTITY_QA_LOGO = createIdentity(QaLogo.QA_LOGO, QaLogo.QA_LOGO.ID);
        public static Identity<QaMessagesRecord, UInteger> IDENTITY_QA_MESSAGES = createIdentity(QaMessages.QA_MESSAGES, QaMessages.QA_MESSAGES.MESSAGEID);
        public static Identity<QaOnlineUserRecord, Integer> IDENTITY_QA_ONLINE_USER = createIdentity(QaOnlineUser.QA_ONLINE_USER, QaOnlineUser.QA_ONLINE_USER.ID);
        public static Identity<QaPagesRecord, UShort> IDENTITY_QA_PAGES = createIdentity(QaPages.QA_PAGES, QaPages.QA_PAGES.PAGEID);
        public static Identity<QaPostsRecord, UInteger> IDENTITY_QA_POSTS = createIdentity(QaPosts.QA_POSTS, QaPosts.QA_POSTS.POSTID);
        public static Identity<QaTopicsRecord, Integer> IDENTITY_QA_TOPICS = createIdentity(QaTopics.QA_TOPICS, QaTopics.QA_TOPICS.ID);
        public static Identity<QaUserbadgesRecord, Integer> IDENTITY_QA_USERBADGES = createIdentity(QaUserbadges.QA_USERBADGES, QaUserbadges.QA_USERBADGES.ID);
        public static Identity<QaUserfieldsRecord, UShort> IDENTITY_QA_USERFIELDS = createIdentity(QaUserfields.QA_USERFIELDS, QaUserfields.QA_USERFIELDS.FIELDID);
        public static Identity<QaUsernoticesRecord, UInteger> IDENTITY_QA_USERNOTICES = createIdentity(QaUsernotices.QA_USERNOTICES, QaUsernotices.QA_USERNOTICES.NOTICEID);
        public static Identity<QaUsersRecord, UInteger> IDENTITY_QA_USERS = createIdentity(QaUsers.QA_USERS, QaUsers.QA_USERS.USERID);
        public static Identity<QaWidgetsRecord, UShort> IDENTITY_QA_WIDGETS = createIdentity(QaWidgets.QA_WIDGETS, QaWidgets.QA_WIDGETS.WIDGETID);
        public static Identity<QaWordsRecord, UInteger> IDENTITY_QA_WORDS = createIdentity(QaWords.QA_WORDS, QaWords.QA_WORDS.WORDID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<QaAchievementsRecord> KEY_QA_ACHIEVEMENTS_USER_ID = createUniqueKey(QaAchievements.QA_ACHIEVEMENTS, "KEY_qa_achievements_user_id", QaAchievements.QA_ACHIEVEMENTS.USER_ID);
        public static final UniqueKey<QaBlobsRecord> KEY_QA_BLOBS_PRIMARY = createUniqueKey(QaBlobs.QA_BLOBS, "KEY_qa_blobs_PRIMARY", QaBlobs.QA_BLOBS.BLOBID);
        public static final UniqueKey<QaBlogCommentsRecord> KEY_QA_BLOG_COMMENTS_PRIMARY = createUniqueKey(QaBlogComments.QA_BLOG_COMMENTS, "KEY_qa_blog_comments_PRIMARY", QaBlogComments.QA_BLOG_COMMENTS.POSTID);
        public static final UniqueKey<QaBlogPostsRecord> KEY_QA_BLOG_POSTS_PRIMARY = createUniqueKey(QaBlogPosts.QA_BLOG_POSTS, "KEY_qa_blog_posts_PRIMARY", QaBlogPosts.QA_BLOG_POSTS.POSTID);
        public static final UniqueKey<QaBlogUsersRecord> KEY_QA_BLOG_USERS_PRIMARY = createUniqueKey(QaBlogUsers.QA_BLOG_USERS, "KEY_qa_blog_users_PRIMARY", QaBlogUsers.QA_BLOG_USERS.USERID);
        public static final UniqueKey<QaCacheRecord> KEY_QA_CACHE_PRIMARY = createUniqueKey(QaCache.QA_CACHE, "KEY_qa_cache_PRIMARY", QaCache.QA_CACHE.TYPE, QaCache.QA_CACHE.CACHEID);
        public static final UniqueKey<QaCategoriesRecord> KEY_QA_CATEGORIES_PRIMARY = createUniqueKey(QaCategories.QA_CATEGORIES, "KEY_qa_categories_PRIMARY", QaCategories.QA_CATEGORIES.CATEGORYID);
        public static final UniqueKey<QaCategoriesRecord> KEY_QA_CATEGORIES_PARENTID = createUniqueKey(QaCategories.QA_CATEGORIES, "KEY_qa_categories_parentid", QaCategories.QA_CATEGORIES.PARENTID, QaCategories.QA_CATEGORIES.TAGS);
        public static final UniqueKey<QaCategoriesRecord> KEY_QA_CATEGORIES_PARENTID_2 = createUniqueKey(QaCategories.QA_CATEGORIES, "KEY_qa_categories_parentid_2", QaCategories.QA_CATEGORIES.PARENTID, QaCategories.QA_CATEGORIES.POSITION);
        public static final UniqueKey<QaCategorymetasRecord> KEY_QA_CATEGORYMETAS_PRIMARY = createUniqueKey(QaCategorymetas.QA_CATEGORYMETAS, "KEY_qa_categorymetas_PRIMARY", QaCategorymetas.QA_CATEGORYMETAS.CATEGORYID, QaCategorymetas.QA_CATEGORYMETAS.TITLE);
        public static final UniqueKey<QaCookiesRecord> KEY_QA_COOKIES_PRIMARY = createUniqueKey(QaCookies.QA_COOKIES, "KEY_qa_cookies_PRIMARY", QaCookies.QA_COOKIES.COOKIEID);
        public static final UniqueKey<QaIplimitsRecord> KEY_QA_IPLIMITS_IP = createUniqueKey(QaIplimits.QA_IPLIMITS, "KEY_qa_iplimits_ip", QaIplimits.QA_IPLIMITS.IP, QaIplimits.QA_IPLIMITS.ACTION);
        public static final UniqueKey<QaLogoRecord> KEY_QA_LOGO_PRIMARY = createUniqueKey(QaLogo.QA_LOGO, "KEY_qa_logo_PRIMARY", QaLogo.QA_LOGO.ID);
        public static final UniqueKey<QaMessagesRecord> KEY_QA_MESSAGES_PRIMARY = createUniqueKey(QaMessages.QA_MESSAGES, "KEY_qa_messages_PRIMARY", QaMessages.QA_MESSAGES.MESSAGEID);
        public static final UniqueKey<QaOnlineUserRecord> KEY_QA_ONLINE_USER_PRIMARY = createUniqueKey(QaOnlineUser.QA_ONLINE_USER, "KEY_qa_online_user_PRIMARY", QaOnlineUser.QA_ONLINE_USER.ID);
        public static final UniqueKey<QaOptionsRecord> KEY_QA_OPTIONS_PRIMARY = createUniqueKey(QaOptions.QA_OPTIONS, "KEY_qa_options_PRIMARY", QaOptions.QA_OPTIONS.TITLE);
        public static final UniqueKey<QaPagesRecord> KEY_QA_PAGES_PRIMARY = createUniqueKey(QaPages.QA_PAGES, "KEY_qa_pages_PRIMARY", QaPages.QA_PAGES.PAGEID);
        public static final UniqueKey<QaPagesRecord> KEY_QA_PAGES_POSITION = createUniqueKey(QaPages.QA_PAGES, "KEY_qa_pages_position", QaPages.QA_PAGES.POSITION);
        public static final UniqueKey<QaPostmetasRecord> KEY_QA_POSTMETAS_PRIMARY = createUniqueKey(QaPostmetas.QA_POSTMETAS, "KEY_qa_postmetas_PRIMARY", QaPostmetas.QA_POSTMETAS.POSTID, QaPostmetas.QA_POSTMETAS.TITLE);
        public static final UniqueKey<QaPostsRecord> KEY_QA_POSTS_PRIMARY = createUniqueKey(QaPosts.QA_POSTS, "KEY_qa_posts_PRIMARY", QaPosts.QA_POSTS.POSTID);
        public static final UniqueKey<QaTagmetasRecord> KEY_QA_TAGMETAS_PRIMARY = createUniqueKey(QaTagmetas.QA_TAGMETAS, "KEY_qa_tagmetas_PRIMARY", QaTagmetas.QA_TAGMETAS.TAG, QaTagmetas.QA_TAGMETAS.TITLE);
        public static final UniqueKey<QaTopicsRecord> KEY_QA_TOPICS_PRIMARY = createUniqueKey(QaTopics.QA_TOPICS, "KEY_qa_topics_PRIMARY", QaTopics.QA_TOPICS.ID);
        public static final UniqueKey<QaUserbadgesRecord> KEY_QA_USERBADGES_PRIMARY = createUniqueKey(QaUserbadges.QA_USERBADGES, "KEY_qa_userbadges_PRIMARY", QaUserbadges.QA_USERBADGES.ID);
        public static final UniqueKey<QaUserfavoritesRecord> KEY_QA_USERFAVORITES_PRIMARY = createUniqueKey(QaUserfavorites.QA_USERFAVORITES, "KEY_qa_userfavorites_PRIMARY", QaUserfavorites.QA_USERFAVORITES.USERID, QaUserfavorites.QA_USERFAVORITES.ENTITYTYPE, QaUserfavorites.QA_USERFAVORITES.ENTITYID);
        public static final UniqueKey<QaUserfieldsRecord> KEY_QA_USERFIELDS_PRIMARY = createUniqueKey(QaUserfields.QA_USERFIELDS, "KEY_qa_userfields_PRIMARY", QaUserfields.QA_USERFIELDS.FIELDID);
        public static final UniqueKey<QaUserlevelsRecord> KEY_QA_USERLEVELS_USERID = createUniqueKey(QaUserlevels.QA_USERLEVELS, "KEY_qa_userlevels_userid", QaUserlevels.QA_USERLEVELS.USERID, QaUserlevels.QA_USERLEVELS.ENTITYTYPE, QaUserlevels.QA_USERLEVELS.ENTITYID);
        public static final UniqueKey<QaUserlimitsRecord> KEY_QA_USERLIMITS_USERID = createUniqueKey(QaUserlimits.QA_USERLIMITS, "KEY_qa_userlimits_userid", QaUserlimits.QA_USERLIMITS.USERID, QaUserlimits.QA_USERLIMITS.ACTION);
        public static final UniqueKey<QaUsermetasRecord> KEY_QA_USERMETAS_PRIMARY = createUniqueKey(QaUsermetas.QA_USERMETAS, "KEY_qa_usermetas_PRIMARY", QaUsermetas.QA_USERMETAS.USERID, QaUsermetas.QA_USERMETAS.TITLE);
        public static final UniqueKey<QaUsernoticesRecord> KEY_QA_USERNOTICES_PRIMARY = createUniqueKey(QaUsernotices.QA_USERNOTICES, "KEY_qa_usernotices_PRIMARY", QaUsernotices.QA_USERNOTICES.NOTICEID);
        public static final UniqueKey<QaUserpointsRecord> KEY_QA_USERPOINTS_PRIMARY = createUniqueKey(QaUserpoints.QA_USERPOINTS, "KEY_qa_userpoints_PRIMARY", QaUserpoints.QA_USERPOINTS.USERID);
        public static final UniqueKey<QaUserprofileRecord> KEY_QA_USERPROFILE_USERID = createUniqueKey(QaUserprofile.QA_USERPROFILE, "KEY_qa_userprofile_userid", QaUserprofile.QA_USERPROFILE.USERID, QaUserprofile.QA_USERPROFILE.TITLE);
        public static final UniqueKey<QaUsersRecord> KEY_QA_USERS_PRIMARY = createUniqueKey(QaUsers.QA_USERS, "KEY_qa_users_PRIMARY", QaUsers.QA_USERS.USERID);
        public static final UniqueKey<QaUservotesRecord> KEY_QA_USERVOTES_USERID = createUniqueKey(QaUservotes.QA_USERVOTES, "KEY_qa_uservotes_userid", QaUservotes.QA_USERVOTES.USERID, QaUservotes.QA_USERVOTES.POSTID);
        public static final UniqueKey<QaWidgetsRecord> KEY_QA_WIDGETS_PRIMARY = createUniqueKey(QaWidgets.QA_WIDGETS, "KEY_qa_widgets_PRIMARY", QaWidgets.QA_WIDGETS.WIDGETID);
        public static final UniqueKey<QaWidgetsRecord> KEY_QA_WIDGETS_POSITION = createUniqueKey(QaWidgets.QA_WIDGETS, "KEY_qa_widgets_position", QaWidgets.QA_WIDGETS.POSITION);
        public static final UniqueKey<QaWordsRecord> KEY_QA_WORDS_PRIMARY = createUniqueKey(QaWords.QA_WORDS, "KEY_qa_words_PRIMARY", QaWords.QA_WORDS.WORDID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<QaCategorymetasRecord, QaCategoriesRecord> QA_CATEGORYMETAS_IBFK_1 = createForeignKey(Keys.KEY_QA_CATEGORIES_PRIMARY, QaCategorymetas.QA_CATEGORYMETAS, "qa_categorymetas_ibfk_1", QaCategorymetas.QA_CATEGORYMETAS.CATEGORYID);
        public static final ForeignKey<QaContentwordsRecord, QaPostsRecord> QA_CONTENTWORDS_IBFK_1 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaContentwords.QA_CONTENTWORDS, "qa_contentwords_ibfk_1", QaContentwords.QA_CONTENTWORDS.POSTID);
        public static final ForeignKey<QaContentwordsRecord, QaWordsRecord> QA_CONTENTWORDS_IBFK_2 = createForeignKey(Keys.KEY_QA_WORDS_PRIMARY, QaContentwords.QA_CONTENTWORDS, "qa_contentwords_ibfk_2", QaContentwords.QA_CONTENTWORDS.WORDID);
        public static final ForeignKey<QaPostmetasRecord, QaPostsRecord> QA_POSTMETAS_IBFK_1 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaPostmetas.QA_POSTMETAS, "qa_postmetas_ibfk_1", QaPostmetas.QA_POSTMETAS.POSTID);
        public static final ForeignKey<QaPostsRecord, QaPostsRecord> QA_POSTS_IBFK_2 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaPosts.QA_POSTS, "qa_posts_ibfk_2", QaPosts.QA_POSTS.PARENTID);
        public static final ForeignKey<QaPostsRecord, QaCategoriesRecord> QA_POSTS_IBFK_3 = createForeignKey(Keys.KEY_QA_CATEGORIES_PRIMARY, QaPosts.QA_POSTS, "qa_posts_ibfk_3", QaPosts.QA_POSTS.CATEGORYID);
        public static final ForeignKey<QaPostsRecord, QaPostsRecord> QA_POSTS_IBFK_4 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaPosts.QA_POSTS, "qa_posts_ibfk_4", QaPosts.QA_POSTS.CLOSEDBYID);
        public static final ForeignKey<QaPosttagsRecord, QaPostsRecord> QA_POSTTAGS_IBFK_1 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaPosttags.QA_POSTTAGS, "qa_posttags_ibfk_1", QaPosttags.QA_POSTTAGS.POSTID);
        public static final ForeignKey<QaPosttagsRecord, QaWordsRecord> QA_POSTTAGS_IBFK_2 = createForeignKey(Keys.KEY_QA_WORDS_PRIMARY, QaPosttags.QA_POSTTAGS, "qa_posttags_ibfk_2", QaPosttags.QA_POSTTAGS.WORDID);
        public static final ForeignKey<QaTagwordsRecord, QaPostsRecord> QA_TAGWORDS_IBFK_1 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaTagwords.QA_TAGWORDS, "qa_tagwords_ibfk_1", QaTagwords.QA_TAGWORDS.POSTID);
        public static final ForeignKey<QaTagwordsRecord, QaWordsRecord> QA_TAGWORDS_IBFK_2 = createForeignKey(Keys.KEY_QA_WORDS_PRIMARY, QaTagwords.QA_TAGWORDS, "qa_tagwords_ibfk_2", QaTagwords.QA_TAGWORDS.WORDID);
        public static final ForeignKey<QaTitlewordsRecord, QaPostsRecord> QA_TITLEWORDS_IBFK_1 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaTitlewords.QA_TITLEWORDS, "qa_titlewords_ibfk_1", QaTitlewords.QA_TITLEWORDS.POSTID);
        public static final ForeignKey<QaTitlewordsRecord, QaWordsRecord> QA_TITLEWORDS_IBFK_2 = createForeignKey(Keys.KEY_QA_WORDS_PRIMARY, QaTitlewords.QA_TITLEWORDS, "qa_titlewords_ibfk_2", QaTitlewords.QA_TITLEWORDS.WORDID);
        public static final ForeignKey<QaUserloginsRecord, QaUsersRecord> QA_USERLOGINS_IBFK_1 = createForeignKey(Keys.KEY_QA_USERS_PRIMARY, QaUserlogins.QA_USERLOGINS, "qa_userlogins_ibfk_1", QaUserlogins.QA_USERLOGINS.USERID);
        public static final ForeignKey<QaUserprofileRecord, QaUsersRecord> QA_USERPROFILE_IBFK_1 = createForeignKey(Keys.KEY_QA_USERS_PRIMARY, QaUserprofile.QA_USERPROFILE, "qa_userprofile_ibfk_1", QaUserprofile.QA_USERPROFILE.USERID);
        public static final ForeignKey<QaUservotesRecord, QaPostsRecord> QA_USERVOTES_IBFK_1 = createForeignKey(Keys.KEY_QA_POSTS_PRIMARY, QaUservotes.QA_USERVOTES, "qa_uservotes_ibfk_1", QaUservotes.QA_USERVOTES.POSTID);
    }
}
