/*
 * This file is generated by jOOQ.
*/
package DBlorg.enums;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum QaPostsType implements EnumType {

    Q("Q"),

    A("A"),

    C("C"),

    Q_HIDDEN("Q_HIDDEN"),

    A_HIDDEN("A_HIDDEN"),

    C_HIDDEN("C_HIDDEN"),

    Q_QUEUED("Q_QUEUED"),

    A_QUEUED("A_QUEUED"),

    C_QUEUED("C_QUEUED"),

    NOTE("NOTE");

    private final String literal;

    private QaPostsType(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "qa_posts_type";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
