/*
 * This file is generated by jOOQ.
*/
package DBnewLogrExtra;


import DBnewLogrExtra.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newlogrextra extends SchemaImpl {

    private static final long serialVersionUID = 967391256;

    /**
     * The reference instance of <code>DBnewLogrExtra</code>
     */
    public static final Newlogrextra NEWLOGREXTRA = new Newlogrextra();

    /**
     * The table <code>DBnewLogrExtra.answers</code>.
     */
    public final Answers ANSWERS = Answers.ANSWERS;

    /**
     * The table <code>DBnewLogrExtra.closed</code>.
     */
    public final Closed CLOSED = Closed.CLOSED;

    /**
     * The table <code>DBnewLogrExtra.comments</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>DBnewLogrExtra.fos_user</code>.
     */
    public final FosUser FOS_USER = FosUser.FOS_USER;

    /**
     * The table <code>DBnewLogrExtra.logger</code>.
     */
    public final Logger LOGGER = Logger.LOGGER;

    /**
     * The table <code>DBnewLogrExtra.logger_actions</code>.
     */
    public final LoggerActions LOGGER_ACTIONS = LoggerActions.LOGGER_ACTIONS;

    /**
     * The table <code>DBnewLogrExtra.messages</code>.
     */
    public final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>DBnewLogrExtra.permissions</code>.
     */
    public final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>DBnewLogrExtra.qs_to_topic</code>.
     */
    public final QsToTopic QS_TO_TOPIC = QsToTopic.QS_TO_TOPIC;

    /**
     * The table <code>DBnewLogrExtra.questions</code>.
     */
    public final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>DBnewLogrExtra.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>DBnewLogrExtra.routes</code>.
     */
    public final Routes ROUTES = Routes.ROUTES;

    /**
     * The table <code>DBnewLogrExtra.seo_profile</code>.
     */
    public final SeoProfile SEO_PROFILE = SeoProfile.SEO_PROFILE;

    /**
     * The table <code>DBnewLogrExtra.seo_redirect</code>.
     */
    public final SeoRedirect SEO_REDIRECT = SeoRedirect.SEO_REDIRECT;

    /**
     * The table <code>DBnewLogrExtra.seo_stationary</code>.
     */
    public final SeoStationary SEO_STATIONARY = SeoStationary.SEO_STATIONARY;

    /**
     * The table <code>DBnewLogrExtra.topics</code>.
     */
    public final Topics TOPICS = Topics.TOPICS;

    /**
     * The table <code>DBnewLogrExtra.user_profile</code>.
     */
    public final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;

    /**
     * The table <code>DBnewLogrExtra.user_to_favorites</code>.
     */
    public final UserToFavorites USER_TO_FAVORITES = UserToFavorites.USER_TO_FAVORITES;

    /**
     * The table <code>DBnewLogrExtra.user_to_votes</code>.
     */
    public final UserToVotes USER_TO_VOTES = UserToVotes.USER_TO_VOTES;

    /**
     * The table <code>DBnewLogrExtra.votes</code>.
     */
    public final Votes VOTES = Votes.VOTES;

    /**
     * No further instances allowed
     */
    private Newlogrextra() {
        super("newLogrExtra", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Answers.ANSWERS,
            Closed.CLOSED,
            Comments.COMMENTS,
            FosUser.FOS_USER,
            Logger.LOGGER,
            LoggerActions.LOGGER_ACTIONS,
            Messages.MESSAGES,
            Permissions.PERMISSIONS,
            QsToTopic.QS_TO_TOPIC,
            Questions.QUESTIONS,
            Roles.ROLES,
            Routes.ROUTES,
            SeoProfile.SEO_PROFILE,
            SeoRedirect.SEO_REDIRECT,
            SeoStationary.SEO_STATIONARY,
            Topics.TOPICS,
            UserProfile.USER_PROFILE,
            UserToFavorites.USER_TO_FAVORITES,
            UserToVotes.USER_TO_VOTES,
            Votes.VOTES);
    }
}
