/*
 * This file is generated by jOOQ.
*/
package DBnewLogrExtra;


import DBnewLogrExtra.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in DBnewLogrExtra
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DBnewLogrExtra.answers</code>.
     */
    public static final Answers ANSWERS = Answers.ANSWERS;

    /**
     * The table <code>DBnewLogrExtra.closed</code>.
     */
    public static final Closed CLOSED = Closed.CLOSED;

    /**
     * The table <code>DBnewLogrExtra.comments</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>DBnewLogrExtra.fos_user</code>.
     */
    public static final FosUser FOS_USER = FosUser.FOS_USER;

    /**
     * The table <code>DBnewLogrExtra.logger</code>.
     */
    public static final Logger LOGGER = Logger.LOGGER;

    /**
     * The table <code>DBnewLogrExtra.logger_actions</code>.
     */
    public static final LoggerActions LOGGER_ACTIONS = LoggerActions.LOGGER_ACTIONS;

    /**
     * The table <code>DBnewLogrExtra.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>DBnewLogrExtra.permissions</code>.
     */
    public static final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>DBnewLogrExtra.qs_to_topic</code>.
     */
    public static final QsToTopic QS_TO_TOPIC = QsToTopic.QS_TO_TOPIC;

    /**
     * The table <code>DBnewLogrExtra.questions</code>.
     */
    public static final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>DBnewLogrExtra.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>DBnewLogrExtra.routes</code>.
     */
    public static final Routes ROUTES = Routes.ROUTES;

    /**
     * The table <code>DBnewLogrExtra.seo_profile</code>.
     */
    public static final SeoProfile SEO_PROFILE = SeoProfile.SEO_PROFILE;

    /**
     * The table <code>DBnewLogrExtra.seo_redirect</code>.
     */
    public static final SeoRedirect SEO_REDIRECT = SeoRedirect.SEO_REDIRECT;

    /**
     * The table <code>DBnewLogrExtra.seo_stationary</code>.
     */
    public static final SeoStationary SEO_STATIONARY = SeoStationary.SEO_STATIONARY;

    /**
     * The table <code>DBnewLogrExtra.topics</code>.
     */
    public static final Topics TOPICS = Topics.TOPICS;

    /**
     * The table <code>DBnewLogrExtra.user_profile</code>.
     */
    public static final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;

    /**
     * The table <code>DBnewLogrExtra.user_to_favorites</code>.
     */
    public static final UserToFavorites USER_TO_FAVORITES = UserToFavorites.USER_TO_FAVORITES;

    /**
     * The table <code>DBnewLogrExtra.user_to_votes</code>.
     */
    public static final UserToVotes USER_TO_VOTES = UserToVotes.USER_TO_VOTES;

    /**
     * The table <code>DBnewLogrExtra.votes</code>.
     */
    public static final Votes VOTES = Votes.VOTES;
}
