/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import DBlorg.Indexes;
import DBlorg.Keys;
import DBlorg.Lorg;
import DBlorg.tables.records.QaBlogCommentsRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaBlogComments extends TableImpl<QaBlogCommentsRecord> {

    private static final long serialVersionUID = -1959021043;

    /**
     * The reference instance of <code>DBlorg.qa_blog_comments</code>
     */
    public static final QaBlogComments QA_BLOG_COMMENTS = new QaBlogComments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QaBlogCommentsRecord> getRecordType() {
        return QaBlogCommentsRecord.class;
    }

    /**
     * The column <code>DBlorg.qa_blog_comments.postid</code>.
     */
    public final TableField<QaBlogCommentsRecord, UInteger> POSTID = createField("postid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>DBlorg.qa_blog_comments.parentid</code>.
     */
    public final TableField<QaBlogCommentsRecord, UInteger> PARENTID = createField("parentid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_blog_comments.posted</code>.
     */
    public final TableField<QaBlogCommentsRecord, Timestamp> POSTED = createField("posted", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_blog_comments.comment</code>.
     */
    public final TableField<QaBlogCommentsRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_blog_comments.userid</code>.
     */
    public final TableField<QaBlogCommentsRecord, UInteger> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_blog_comments.updated</code>.
     */
    public final TableField<QaBlogCommentsRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>DBlorg.qa_blog_comments.format</code>.
     */
    public final TableField<QaBlogCommentsRecord, String> FORMAT = createField("format", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>DBlorg.qa_blog_comments</code> table reference
     */
    public QaBlogComments() {
        this(DSL.name("qa_blog_comments"), null);
    }

    /**
     * Create an aliased <code>DBlorg.qa_blog_comments</code> table reference
     */
    public QaBlogComments(String alias) {
        this(DSL.name(alias), QA_BLOG_COMMENTS);
    }

    /**
     * Create an aliased <code>DBlorg.qa_blog_comments</code> table reference
     */
    public QaBlogComments(Name alias) {
        this(alias, QA_BLOG_COMMENTS);
    }

    private QaBlogComments(Name alias, Table<QaBlogCommentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QaBlogComments(Name alias, Table<QaBlogCommentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorg.LORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.QA_BLOG_COMMENTS_PARENTID, Indexes.QA_BLOG_COMMENTS_POSTED, Indexes.QA_BLOG_COMMENTS_PRIMARY, Indexes.QA_BLOG_COMMENTS_UPDATED);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<QaBlogCommentsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_QA_BLOG_COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QaBlogCommentsRecord> getPrimaryKey() {
        return Keys.KEY_QA_BLOG_COMMENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QaBlogCommentsRecord>> getKeys() {
        return Arrays.<UniqueKey<QaBlogCommentsRecord>>asList(Keys.KEY_QA_BLOG_COMMENTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogComments as(String alias) {
        return new QaBlogComments(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogComments as(Name alias) {
        return new QaBlogComments(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QaBlogComments rename(String name) {
        return new QaBlogComments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QaBlogComments rename(Name name) {
        return new QaBlogComments(name, null);
    }
}
