/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import DBlorg.Indexes;
import DBlorg.Keys;
import DBlorg.Lorg;
import DBlorg.enums.QaContentwordsType;
import DBlorg.tables.records.QaContentwordsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaContentwords extends TableImpl<QaContentwordsRecord> {

    private static final long serialVersionUID = 1976520892;

    /**
     * The reference instance of <code>DBlorg.qa_contentwords</code>
     */
    public static final QaContentwords QA_CONTENTWORDS = new QaContentwords();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QaContentwordsRecord> getRecordType() {
        return QaContentwordsRecord.class;
    }

    /**
     * The column <code>DBlorg.qa_contentwords.postid</code>.
     */
    public final TableField<QaContentwordsRecord, UInteger> POSTID = createField("postid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_contentwords.wordid</code>.
     */
    public final TableField<QaContentwordsRecord, UInteger> WORDID = createField("wordid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_contentwords.count</code>.
     */
    public final TableField<QaContentwordsRecord, UByte> COUNT = createField("count", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_contentwords.type</code>.
     */
    public final TableField<QaContentwordsRecord, QaContentwordsType> TYPE = createField("type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(QaContentwordsType.class), this, "");

    /**
     * The column <code>DBlorg.qa_contentwords.questionid</code>.
     */
    public final TableField<QaContentwordsRecord, UInteger> QUESTIONID = createField("questionid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>DBlorg.qa_contentwords</code> table reference
     */
    public QaContentwords() {
        this(DSL.name("qa_contentwords"), null);
    }

    /**
     * Create an aliased <code>DBlorg.qa_contentwords</code> table reference
     */
    public QaContentwords(String alias) {
        this(DSL.name(alias), QA_CONTENTWORDS);
    }

    /**
     * Create an aliased <code>DBlorg.qa_contentwords</code> table reference
     */
    public QaContentwords(Name alias) {
        this(alias, QA_CONTENTWORDS);
    }

    private QaContentwords(Name alias, Table<QaContentwordsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QaContentwords(Name alias, Table<QaContentwordsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorg.LORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.QA_CONTENTWORDS_POSTID, Indexes.QA_CONTENTWORDS_WORDID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<QaContentwordsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QaContentwordsRecord, ?>>asList(Keys.QA_CONTENTWORDS_IBFK_1, Keys.QA_CONTENTWORDS_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwords as(String alias) {
        return new QaContentwords(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwords as(Name alias) {
        return new QaContentwords(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QaContentwords rename(String name) {
        return new QaContentwords(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QaContentwords rename(Name name) {
        return new QaContentwords(name, null);
    }
}
