/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import DBlorg.Indexes;
import DBlorg.Keys;
import DBlorg.Lorg;
import DBlorg.tables.records.QaTitlewordsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaTitlewords extends TableImpl<QaTitlewordsRecord> {

    private static final long serialVersionUID = -1494120654;

    /**
     * The reference instance of <code>DBlorg.qa_titlewords</code>
     */
    public static final QaTitlewords QA_TITLEWORDS = new QaTitlewords();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QaTitlewordsRecord> getRecordType() {
        return QaTitlewordsRecord.class;
    }

    /**
     * The column <code>DBlorg.qa_titlewords.postid</code>.
     */
    public final TableField<QaTitlewordsRecord, UInteger> POSTID = createField("postid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_titlewords.wordid</code>.
     */
    public final TableField<QaTitlewordsRecord, UInteger> WORDID = createField("wordid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>DBlorg.qa_titlewords</code> table reference
     */
    public QaTitlewords() {
        this(DSL.name("qa_titlewords"), null);
    }

    /**
     * Create an aliased <code>DBlorg.qa_titlewords</code> table reference
     */
    public QaTitlewords(String alias) {
        this(DSL.name(alias), QA_TITLEWORDS);
    }

    /**
     * Create an aliased <code>DBlorg.qa_titlewords</code> table reference
     */
    public QaTitlewords(Name alias) {
        this(alias, QA_TITLEWORDS);
    }

    private QaTitlewords(Name alias, Table<QaTitlewordsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QaTitlewords(Name alias, Table<QaTitlewordsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorg.LORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.QA_TITLEWORDS_POSTID, Indexes.QA_TITLEWORDS_WORDID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<QaTitlewordsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QaTitlewordsRecord, ?>>asList(Keys.QA_TITLEWORDS_IBFK_1, Keys.QA_TITLEWORDS_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTitlewords as(String alias) {
        return new QaTitlewords(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTitlewords as(Name alias) {
        return new QaTitlewords(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QaTitlewords rename(String name) {
        return new QaTitlewords(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QaTitlewords rename(Name name) {
        return new QaTitlewords(name, null);
    }
}
