/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import DBlorg.Indexes;
import DBlorg.Keys;
import DBlorg.Lorg;
import DBlorg.tables.records.QaUserprofileRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserprofile extends TableImpl<QaUserprofileRecord> {

    private static final long serialVersionUID = 406340512;

    /**
     * The reference instance of <code>DBlorg.qa_userprofile</code>
     */
    public static final QaUserprofile QA_USERPROFILE = new QaUserprofile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QaUserprofileRecord> getRecordType() {
        return QaUserprofileRecord.class;
    }

    /**
     * The column <code>DBlorg.qa_userprofile.userid</code>.
     */
    public final TableField<QaUserprofileRecord, UInteger> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userprofile.title</code>.
     */
    public final TableField<QaUserprofileRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userprofile.content</code>.
     */
    public final TableField<QaUserprofileRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR(8000).nullable(false), this, "");

    /**
     * Create a <code>DBlorg.qa_userprofile</code> table reference
     */
    public QaUserprofile() {
        this(DSL.name("qa_userprofile"), null);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userprofile</code> table reference
     */
    public QaUserprofile(String alias) {
        this(DSL.name(alias), QA_USERPROFILE);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userprofile</code> table reference
     */
    public QaUserprofile(Name alias) {
        this(alias, QA_USERPROFILE);
    }

    private QaUserprofile(Name alias, Table<QaUserprofileRecord> aliased) {
        this(alias, aliased, null);
    }

    private QaUserprofile(Name alias, Table<QaUserprofileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorg.LORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.QA_USERPROFILE_USERID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QaUserprofileRecord>> getKeys() {
        return Arrays.<UniqueKey<QaUserprofileRecord>>asList(Keys.KEY_QA_USERPROFILE_USERID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<QaUserprofileRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QaUserprofileRecord, ?>>asList(Keys.QA_USERPROFILE_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserprofile as(String alias) {
        return new QaUserprofile(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserprofile as(Name alias) {
        return new QaUserprofile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserprofile rename(String name) {
        return new QaUserprofile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserprofile rename(Name name) {
        return new QaUserprofile(name, null);
    }
}
