/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import DBlorg.Indexes;
import DBlorg.Keys;
import DBlorg.Lorg;
import DBlorg.tables.records.QaUserloginsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserlogins extends TableImpl<QaUserloginsRecord> {

    private static final long serialVersionUID = -1381769737;

    /**
     * The reference instance of <code>DBlorg.qa_userlogins</code>
     */
    public static final QaUserlogins QA_USERLOGINS = new QaUserlogins();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QaUserloginsRecord> getRecordType() {
        return QaUserloginsRecord.class;
    }

    /**
     * The column <code>DBlorg.qa_userlogins.userid</code>.
     */
    public final TableField<QaUserloginsRecord, UInteger> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userlogins.source</code>.
     */
    public final TableField<QaUserloginsRecord, String> SOURCE = createField("source", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userlogins.identifier</code>.
     */
    public final TableField<QaUserloginsRecord, byte[]> IDENTIFIER = createField("identifier", org.jooq.impl.SQLDataType.VARBINARY(1024).nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userlogins.identifiermd5</code>.
     */
    public final TableField<QaUserloginsRecord, byte[]> IDENTIFIERMD5 = createField("identifiermd5", org.jooq.impl.SQLDataType.BINARY(16).nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userlogins.oemail</code>.
     */
    public final TableField<QaUserloginsRecord, String> OEMAIL = createField("oemail", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>DBlorg.qa_userlogins.ohandle</code>.
     */
    public final TableField<QaUserloginsRecord, String> OHANDLE = createField("ohandle", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * Create a <code>DBlorg.qa_userlogins</code> table reference
     */
    public QaUserlogins() {
        this(DSL.name("qa_userlogins"), null);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userlogins</code> table reference
     */
    public QaUserlogins(String alias) {
        this(DSL.name(alias), QA_USERLOGINS);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userlogins</code> table reference
     */
    public QaUserlogins(Name alias) {
        this(alias, QA_USERLOGINS);
    }

    private QaUserlogins(Name alias, Table<QaUserloginsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QaUserlogins(Name alias, Table<QaUserloginsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorg.LORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.QA_USERLOGINS_SOURCE, Indexes.QA_USERLOGINS_USERID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<QaUserloginsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QaUserloginsRecord, ?>>asList(Keys.QA_USERLOGINS_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserlogins as(String alias) {
        return new QaUserlogins(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserlogins as(Name alias) {
        return new QaUserlogins(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserlogins rename(String name) {
        return new QaUserlogins(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserlogins rename(Name name) {
        return new QaUserlogins(name, null);
    }
}
