/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import DBlorg.Indexes;
import DBlorg.Keys;
import DBlorg.Lorg;
import DBlorg.tables.records.QaUserfavoritesRecord;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserfavorites extends TableImpl<QaUserfavoritesRecord> {

    private static final long serialVersionUID = 247335480;

    /**
     * The reference instance of <code>DBlorg.qa_userfavorites</code>
     */
    public static final QaUserfavorites QA_USERFAVORITES = new QaUserfavorites();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QaUserfavoritesRecord> getRecordType() {
        return QaUserfavoritesRecord.class;
    }

    /**
     * The column <code>DBlorg.qa_userfavorites.userid</code>.
     */
    public final TableField<QaUserfavoritesRecord, String> USERID = createField("userid", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userfavorites.entitytype</code>.
     */
    public final TableField<QaUserfavoritesRecord, String> ENTITYTYPE = createField("entitytype", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userfavorites.entityid</code>.
     */
    public final TableField<QaUserfavoritesRecord, UInteger> ENTITYID = createField("entityid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userfavorites.nouserevents</code>.
     */
    public final TableField<QaUserfavoritesRecord, UByte> NOUSEREVENTS = createField("nouserevents", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>DBlorg.qa_userfavorites</code> table reference
     */
    public QaUserfavorites() {
        this(DSL.name("qa_userfavorites"), null);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userfavorites</code> table reference
     */
    public QaUserfavorites(String alias) {
        this(DSL.name(alias), QA_USERFAVORITES);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userfavorites</code> table reference
     */
    public QaUserfavorites(Name alias) {
        this(alias, QA_USERFAVORITES);
    }

    private QaUserfavorites(Name alias, Table<QaUserfavoritesRecord> aliased) {
        this(alias, aliased, null);
    }

    private QaUserfavorites(Name alias, Table<QaUserfavoritesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorg.LORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.QA_USERFAVORITES_ENTITYTYPE, Indexes.QA_USERFAVORITES_PRIMARY, Indexes.QA_USERFAVORITES_USERID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QaUserfavoritesRecord> getPrimaryKey() {
        return Keys.KEY_QA_USERFAVORITES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QaUserfavoritesRecord>> getKeys() {
        return Arrays.<UniqueKey<QaUserfavoritesRecord>>asList(Keys.KEY_QA_USERFAVORITES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfavorites as(String alias) {
        return new QaUserfavorites(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfavorites as(Name alias) {
        return new QaUserfavorites(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserfavorites rename(String name) {
        return new QaUserfavorites(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserfavorites rename(Name name) {
        return new QaUserfavorites(name, null);
    }
}
