/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import DBlorg.Indexes;
import DBlorg.Keys;
import DBlorg.Lorg;
import DBlorg.tables.records.QaUserfieldsRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserfields extends TableImpl<QaUserfieldsRecord> {

    private static final long serialVersionUID = 1948075798;

    /**
     * The reference instance of <code>DBlorg.qa_userfields</code>
     */
    public static final QaUserfields QA_USERFIELDS = new QaUserfields();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QaUserfieldsRecord> getRecordType() {
        return QaUserfieldsRecord.class;
    }

    /**
     * The column <code>DBlorg.qa_userfields.fieldid</code>.
     */
    public final TableField<QaUserfieldsRecord, UShort> FIELDID = createField("fieldid", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>DBlorg.qa_userfields.title</code>.
     */
    public final TableField<QaUserfieldsRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userfields.content</code>.
     */
    public final TableField<QaUserfieldsRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>DBlorg.qa_userfields.position</code>.
     */
    public final TableField<QaUserfieldsRecord, UShort> POSITION = createField("position", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userfields.flags</code>.
     */
    public final TableField<QaUserfieldsRecord, UByte> FLAGS = createField("flags", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>DBlorg.qa_userfields.permit</code>.
     */
    public final TableField<QaUserfieldsRecord, UByte> PERMIT = createField("permit", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * Create a <code>DBlorg.qa_userfields</code> table reference
     */
    public QaUserfields() {
        this(DSL.name("qa_userfields"), null);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userfields</code> table reference
     */
    public QaUserfields(String alias) {
        this(DSL.name(alias), QA_USERFIELDS);
    }

    /**
     * Create an aliased <code>DBlorg.qa_userfields</code> table reference
     */
    public QaUserfields(Name alias) {
        this(alias, QA_USERFIELDS);
    }

    private QaUserfields(Name alias, Table<QaUserfieldsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QaUserfields(Name alias, Table<QaUserfieldsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lorg.LORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.QA_USERFIELDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<QaUserfieldsRecord, UShort> getIdentity() {
        return Keys.IDENTITY_QA_USERFIELDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QaUserfieldsRecord> getPrimaryKey() {
        return Keys.KEY_QA_USERFIELDS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QaUserfieldsRecord>> getKeys() {
        return Arrays.<UniqueKey<QaUserfieldsRecord>>asList(Keys.KEY_QA_USERFIELDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfields as(String alias) {
        return new QaUserfields(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfields as(Name alias) {
        return new QaUserfields(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserfields rename(String name) {
        return new QaUserfields(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QaUserfields rename(Name name) {
        return new QaUserfields(name, null);
    }
}
