/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaBlogUsers;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaBlogUsersRecord extends UpdatableRecordImpl<QaBlogUsersRecord> implements Record4<UInteger, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1744745485;

    /**
     * Setter for <code>DBlorg.qa_blog_users.userid</code>.
     */
    public void setUserid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_users.userid</code>.
     */
    public UInteger getUserid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_users.lastposted</code>.
     */
    public void setLastposted(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_users.lastposted</code>.
     */
    public Timestamp getLastposted() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_users.lastpolled</code>.
     */
    public void setLastpolled(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_users.lastpolled</code>.
     */
    public Timestamp getLastpolled() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_users.kickeduntil</code>.
     */
    public void setKickeduntil(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_users.kickeduntil</code>.
     */
    public Timestamp getKickeduntil() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QaBlogUsers.QA_BLOG_USERS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return QaBlogUsers.QA_BLOG_USERS.LASTPOSTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return QaBlogUsers.QA_BLOG_USERS.LASTPOLLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return QaBlogUsers.QA_BLOG_USERS.KICKEDUNTIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getLastposted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getLastpolled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getKickeduntil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getLastposted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLastpolled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getKickeduntil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogUsersRecord value1(UInteger value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogUsersRecord value2(Timestamp value) {
        setLastposted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogUsersRecord value3(Timestamp value) {
        setLastpolled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogUsersRecord value4(Timestamp value) {
        setKickeduntil(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogUsersRecord values(UInteger value1, Timestamp value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaBlogUsersRecord
     */
    public QaBlogUsersRecord() {
        super(QaBlogUsers.QA_BLOG_USERS);
    }

    /**
     * Create a detached, initialised QaBlogUsersRecord
     */
    public QaBlogUsersRecord(UInteger userid, Timestamp lastposted, Timestamp lastpolled, Timestamp kickeduntil) {
        super(QaBlogUsers.QA_BLOG_USERS);

        set(0, userid);
        set(1, lastposted);
        set(2, lastpolled);
        set(3, kickeduntil);
    }
}
