/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaBlogComments;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaBlogCommentsRecord extends UpdatableRecordImpl<QaBlogCommentsRecord> implements Record7<UInteger, UInteger, Timestamp, String, UInteger, Timestamp, String> {

    private static final long serialVersionUID = 8608078;

    /**
     * Setter for <code>DBlorg.qa_blog_comments.postid</code>.
     */
    public void setPostid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_comments.postid</code>.
     */
    public UInteger getPostid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_comments.parentid</code>.
     */
    public void setParentid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_comments.parentid</code>.
     */
    public UInteger getParentid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_comments.posted</code>.
     */
    public void setPosted(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_comments.posted</code>.
     */
    public Timestamp getPosted() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_comments.comment</code>.
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_comments.comment</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_comments.userid</code>.
     */
    public void setUserid(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_comments.userid</code>.
     */
    public UInteger getUserid() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_comments.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_comments.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>DBlorg.qa_blog_comments.format</code>.
     */
    public void setFormat(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DBlorg.qa_blog_comments.format</code>.
     */
    public String getFormat() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, Timestamp, String, UInteger, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, Timestamp, String, UInteger, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QaBlogComments.QA_BLOG_COMMENTS.POSTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return QaBlogComments.QA_BLOG_COMMENTS.PARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return QaBlogComments.QA_BLOG_COMMENTS.POSTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return QaBlogComments.QA_BLOG_COMMENTS.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return QaBlogComments.QA_BLOG_COMMENTS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return QaBlogComments.QA_BLOG_COMMENTS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return QaBlogComments.QA_BLOG_COMMENTS.FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getPosted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getPosted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord value1(UInteger value) {
        setPostid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord value2(UInteger value) {
        setParentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord value3(Timestamp value) {
        setPosted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord value4(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord value5(UInteger value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord value6(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord value7(String value) {
        setFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaBlogCommentsRecord values(UInteger value1, UInteger value2, Timestamp value3, String value4, UInteger value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaBlogCommentsRecord
     */
    public QaBlogCommentsRecord() {
        super(QaBlogComments.QA_BLOG_COMMENTS);
    }

    /**
     * Create a detached, initialised QaBlogCommentsRecord
     */
    public QaBlogCommentsRecord(UInteger postid, UInteger parentid, Timestamp posted, String comment, UInteger userid, Timestamp updated, String format) {
        super(QaBlogComments.QA_BLOG_COMMENTS);

        set(0, postid);
        set(1, parentid);
        set(2, posted);
        set(3, comment);
        set(4, userid);
        set(5, updated);
        set(6, format);
    }
}
