/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaCache;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaCacheRecord extends UpdatableRecordImpl<QaCacheRecord> implements Record5<String, ULong, byte[], Timestamp, Timestamp> {

    private static final long serialVersionUID = 2120280025;

    /**
     * Setter for <code>DBlorg.qa_cache.type</code>.
     */
    public void setType(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cache.type</code>.
     */
    public String getType() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_cache.cacheid</code>.
     */
    public void setCacheid(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cache.cacheid</code>.
     */
    public ULong getCacheid() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_cache.content</code>.
     */
    public void setContent(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cache.content</code>.
     */
    public byte[] getContent() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_cache.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cache.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_cache.lastread</code>.
     */
    public void setLastread(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cache.lastread</code>.
     */
    public Timestamp getLastread() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, ULong, byte[], Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, ULong, byte[], Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return QaCache.QA_CACHE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return QaCache.QA_CACHE.CACHEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return QaCache.QA_CACHE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return QaCache.QA_CACHE.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return QaCache.QA_CACHE.LASTREAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getCacheid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastread();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getCacheid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastread();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCacheRecord value1(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCacheRecord value2(ULong value) {
        setCacheid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCacheRecord value3(byte... value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCacheRecord value4(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCacheRecord value5(Timestamp value) {
        setLastread(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCacheRecord values(String value1, ULong value2, byte[] value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaCacheRecord
     */
    public QaCacheRecord() {
        super(QaCache.QA_CACHE);
    }

    /**
     * Create a detached, initialised QaCacheRecord
     */
    public QaCacheRecord(String type, ULong cacheid, byte[] content, Timestamp created, Timestamp lastread) {
        super(QaCache.QA_CACHE);

        set(0, type);
        set(1, cacheid);
        set(2, content);
        set(3, created);
        set(4, lastread);
    }
}
