/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaCookies;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaCookiesRecord extends UpdatableRecordImpl<QaCookiesRecord> implements Record5<ULong, Timestamp, UInteger, Timestamp, UInteger> {

    private static final long serialVersionUID = -1694257379;

    /**
     * Setter for <code>DBlorg.qa_cookies.cookieid</code>.
     */
    public void setCookieid(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cookies.cookieid</code>.
     */
    public ULong getCookieid() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_cookies.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cookies.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_cookies.createip</code>.
     */
    public void setCreateip(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cookies.createip</code>.
     */
    public UInteger getCreateip() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_cookies.written</code>.
     */
    public void setWritten(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cookies.written</code>.
     */
    public Timestamp getWritten() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_cookies.writeip</code>.
     */
    public void setWriteip(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_cookies.writeip</code>.
     */
    public UInteger getWriteip() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, Timestamp, UInteger, Timestamp, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, Timestamp, UInteger, Timestamp, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return QaCookies.QA_COOKIES.COOKIEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return QaCookies.QA_COOKIES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return QaCookies.QA_COOKIES.CREATEIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return QaCookies.QA_COOKIES.WRITTEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return QaCookies.QA_COOKIES.WRITEIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getCookieid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getCreateip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getWritten();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getWriteip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getCookieid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getCreateip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getWritten();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getWriteip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCookiesRecord value1(ULong value) {
        setCookieid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCookiesRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCookiesRecord value3(UInteger value) {
        setCreateip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCookiesRecord value4(Timestamp value) {
        setWritten(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCookiesRecord value5(UInteger value) {
        setWriteip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaCookiesRecord values(ULong value1, Timestamp value2, UInteger value3, Timestamp value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaCookiesRecord
     */
    public QaCookiesRecord() {
        super(QaCookies.QA_COOKIES);
    }

    /**
     * Create a detached, initialised QaCookiesRecord
     */
    public QaCookiesRecord(ULong cookieid, Timestamp created, UInteger createip, Timestamp written, UInteger writeip) {
        super(QaCookies.QA_COOKIES);

        set(0, cookieid);
        set(1, created);
        set(2, createip);
        set(3, written);
        set(4, writeip);
    }
}
