/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.enums.QaContentwordsType;
import DBlorg.tables.QaContentwords;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaContentwordsRecord extends TableRecordImpl<QaContentwordsRecord> implements Record5<UInteger, UInteger, UByte, QaContentwordsType, UInteger> {

    private static final long serialVersionUID = -846497453;

    /**
     * Setter for <code>DBlorg.qa_contentwords.postid</code>.
     */
    public void setPostid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_contentwords.postid</code>.
     */
    public UInteger getPostid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_contentwords.wordid</code>.
     */
    public void setWordid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_contentwords.wordid</code>.
     */
    public UInteger getWordid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_contentwords.count</code>.
     */
    public void setCount(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_contentwords.count</code>.
     */
    public UByte getCount() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_contentwords.type</code>.
     */
    public void setType(QaContentwordsType value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_contentwords.type</code>.
     */
    public QaContentwordsType getType() {
        return (QaContentwordsType) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_contentwords.questionid</code>.
     */
    public void setQuestionid(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_contentwords.questionid</code>.
     */
    public UInteger getQuestionid() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UByte, QaContentwordsType, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UByte, QaContentwordsType, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QaContentwords.QA_CONTENTWORDS.POSTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return QaContentwords.QA_CONTENTWORDS.WORDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return QaContentwords.QA_CONTENTWORDS.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<QaContentwordsType> field4() {
        return QaContentwords.QA_CONTENTWORDS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return QaContentwords.QA_CONTENTWORDS.QUESTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsType component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsType value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsRecord value1(UInteger value) {
        setPostid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsRecord value2(UInteger value) {
        setWordid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsRecord value3(UByte value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsRecord value4(QaContentwordsType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsRecord value5(UInteger value) {
        setQuestionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaContentwordsRecord values(UInteger value1, UInteger value2, UByte value3, QaContentwordsType value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaContentwordsRecord
     */
    public QaContentwordsRecord() {
        super(QaContentwords.QA_CONTENTWORDS);
    }

    /**
     * Create a detached, initialised QaContentwordsRecord
     */
    public QaContentwordsRecord(UInteger postid, UInteger wordid, UByte count, QaContentwordsType type, UInteger questionid) {
        super(QaContentwords.QA_CONTENTWORDS);

        set(0, postid);
        set(1, wordid);
        set(2, count);
        set(3, type);
        set(4, questionid);
    }
}
