/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaOnlineUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaOnlineUserRecord extends UpdatableRecordImpl<QaOnlineUserRecord> implements Record4<Integer, Integer, String, Timestamp> {

    private static final long serialVersionUID = 2028525825;

    /**
     * Setter for <code>DBlorg.qa_online_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_online_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_online_user.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_online_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_online_user.ip</code>.
     */
    public void setIp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_online_user.ip</code>.
     */
    public String getIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_online_user.last_activity</code>.
     */
    public void setLastActivity(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_online_user.last_activity</code>.
     */
    public Timestamp getLastActivity() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return QaOnlineUser.QA_ONLINE_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return QaOnlineUser.QA_ONLINE_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return QaOnlineUser.QA_ONLINE_USER.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return QaOnlineUser.QA_ONLINE_USER.LAST_ACTIVITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getLastActivity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getLastActivity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaOnlineUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaOnlineUserRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaOnlineUserRecord value3(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaOnlineUserRecord value4(Timestamp value) {
        setLastActivity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaOnlineUserRecord values(Integer value1, Integer value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaOnlineUserRecord
     */
    public QaOnlineUserRecord() {
        super(QaOnlineUser.QA_ONLINE_USER);
    }

    /**
     * Create a detached, initialised QaOnlineUserRecord
     */
    public QaOnlineUserRecord(Integer id, Integer userId, String ip, Timestamp lastActivity) {
        super(QaOnlineUser.QA_ONLINE_USER);

        set(0, id);
        set(1, userId);
        set(2, ip);
        set(3, lastActivity);
    }
}
