/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaPosttags;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaPosttagsRecord extends TableRecordImpl<QaPosttagsRecord> implements Record3<UInteger, UInteger, Timestamp> {

    private static final long serialVersionUID = 1199888474;

    /**
     * Setter for <code>DBlorg.qa_posttags.postid</code>.
     */
    public void setPostid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posttags.postid</code>.
     */
    public UInteger getPostid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_posttags.wordid</code>.
     */
    public void setWordid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posttags.wordid</code>.
     */
    public UInteger getWordid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_posttags.postcreated</code>.
     */
    public void setPostcreated(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posttags.postcreated</code>.
     */
    public Timestamp getPostcreated() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QaPosttags.QA_POSTTAGS.POSTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return QaPosttags.QA_POSTTAGS.WORDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return QaPosttags.QA_POSTTAGS.POSTCREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getPostcreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getPostcreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaPosttagsRecord value1(UInteger value) {
        setPostid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaPosttagsRecord value2(UInteger value) {
        setWordid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaPosttagsRecord value3(Timestamp value) {
        setPostcreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaPosttagsRecord values(UInteger value1, UInteger value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaPosttagsRecord
     */
    public QaPosttagsRecord() {
        super(QaPosttags.QA_POSTTAGS);
    }

    /**
     * Create a detached, initialised QaPosttagsRecord
     */
    public QaPosttagsRecord(UInteger postid, UInteger wordid, Timestamp postcreated) {
        super(QaPosttags.QA_POSTTAGS);

        set(0, postid);
        set(1, wordid);
        set(2, postcreated);
    }
}
