/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.enums.QaPostsType;
import DBlorg.tables.QaPosts;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaPostsRecord extends UpdatableRecordImpl<QaPostsRecord> {

    private static final long serialVersionUID = -1459192604;

    /**
     * Setter for <code>DBlorg.qa_posts.postid</code>.
     */
    public void setPostid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.postid</code>.
     */
    public UInteger getPostid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.type</code>.
     */
    public void setType(QaPostsType value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.type</code>.
     */
    public QaPostsType getType() {
        return (QaPostsType) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.parentid</code>.
     */
    public void setParentid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.parentid</code>.
     */
    public UInteger getParentid() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.categoryid</code>.
     */
    public void setCategoryid(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.categoryid</code>.
     */
    public UInteger getCategoryid() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.catidpath1</code>.
     */
    public void setCatidpath1(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.catidpath1</code>.
     */
    public UInteger getCatidpath1() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.catidpath2</code>.
     */
    public void setCatidpath2(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.catidpath2</code>.
     */
    public UInteger getCatidpath2() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.catidpath3</code>.
     */
    public void setCatidpath3(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.catidpath3</code>.
     */
    public UInteger getCatidpath3() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.acount</code>.
     */
    public void setAcount(UShort value) {
        set(7, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.acount</code>.
     */
    public UShort getAcount() {
        return (UShort) get(7);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.amaxvote</code>.
     */
    public void setAmaxvote(UShort value) {
        set(8, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.amaxvote</code>.
     */
    public UShort getAmaxvote() {
        return (UShort) get(8);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.selchildid</code>.
     */
    public void setSelchildid(UInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.selchildid</code>.
     */
    public UInteger getSelchildid() {
        return (UInteger) get(9);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.closedbyid</code>.
     */
    public void setClosedbyid(UInteger value) {
        set(10, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.closedbyid</code>.
     */
    public UInteger getClosedbyid() {
        return (UInteger) get(10);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.userid</code>.
     */
    public void setUserid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.userid</code>.
     */
    public String getUserid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.cookieid</code>.
     */
    public void setCookieid(ULong value) {
        set(12, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.cookieid</code>.
     */
    public ULong getCookieid() {
        return (ULong) get(12);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.createip</code>.
     */
    public void setCreateip(UInteger value) {
        set(13, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.createip</code>.
     */
    public UInteger getCreateip() {
        return (UInteger) get(13);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.lastuserid</code>.
     */
    public void setLastuserid(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.lastuserid</code>.
     */
    public String getLastuserid() {
        return (String) get(14);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.lastip</code>.
     */
    public void setLastip(UInteger value) {
        set(15, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.lastip</code>.
     */
    public UInteger getLastip() {
        return (UInteger) get(15);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.upvotes</code>.
     */
    public void setUpvotes(UShort value) {
        set(16, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.upvotes</code>.
     */
    public UShort getUpvotes() {
        return (UShort) get(16);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.downvotes</code>.
     */
    public void setDownvotes(UShort value) {
        set(17, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.downvotes</code>.
     */
    public UShort getDownvotes() {
        return (UShort) get(17);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.netvotes</code>.
     */
    public void setNetvotes(Short value) {
        set(18, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.netvotes</code>.
     */
    public Short getNetvotes() {
        return (Short) get(18);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.lastviewip</code>.
     */
    public void setLastviewip(UInteger value) {
        set(19, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.lastviewip</code>.
     */
    public UInteger getLastviewip() {
        return (UInteger) get(19);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.views</code>.
     */
    public void setViews(UInteger value) {
        set(20, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.views</code>.
     */
    public UInteger getViews() {
        return (UInteger) get(20);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.hotness</code>.
     */
    public void setHotness(Double value) {
        set(21, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.hotness</code>.
     */
    public Double getHotness() {
        return (Double) get(21);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.flagcount</code>.
     */
    public void setFlagcount(UByte value) {
        set(22, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.flagcount</code>.
     */
    public UByte getFlagcount() {
        return (UByte) get(22);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.format</code>.
     */
    public void setFormat(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.format</code>.
     */
    public String getFormat() {
        return (String) get(23);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(24, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(24);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(25, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(25);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.updatetype</code>.
     */
    public void setUpdatetype(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.updatetype</code>.
     */
    public String getUpdatetype() {
        return (String) get(26);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.title</code>.
     */
    public void setTitle(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.title</code>.
     */
    public String getTitle() {
        return (String) get(27);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.content</code>.
     */
    public void setContent(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.content</code>.
     */
    public String getContent() {
        return (String) get(28);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.tags</code>.
     */
    public void setTags(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.tags</code>.
     */
    public String getTags() {
        return (String) get(29);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.name</code>.
     */
    public void setName(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.name</code>.
     */
    public String getName() {
        return (String) get(30);
    }

    /**
     * Setter for <code>DBlorg.qa_posts.notify</code>.
     */
    public void setNotify(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>DBlorg.qa_posts.notify</code>.
     */
    public String getNotify() {
        return (String) get(31);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaPostsRecord
     */
    public QaPostsRecord() {
        super(QaPosts.QA_POSTS);
    }

    /**
     * Create a detached, initialised QaPostsRecord
     */
    public QaPostsRecord(UInteger postid, QaPostsType type, UInteger parentid, UInteger categoryid, UInteger catidpath1, UInteger catidpath2, UInteger catidpath3, UShort acount, UShort amaxvote, UInteger selchildid, UInteger closedbyid, String userid, ULong cookieid, UInteger createip, String lastuserid, UInteger lastip, UShort upvotes, UShort downvotes, Short netvotes, UInteger lastviewip, UInteger views, Double hotness, UByte flagcount, String format, Timestamp created, Timestamp updated, String updatetype, String title, String content, String tags, String name, String notify) {
        super(QaPosts.QA_POSTS);

        set(0, postid);
        set(1, type);
        set(2, parentid);
        set(3, categoryid);
        set(4, catidpath1);
        set(5, catidpath2);
        set(6, catidpath3);
        set(7, acount);
        set(8, amaxvote);
        set(9, selchildid);
        set(10, closedbyid);
        set(11, userid);
        set(12, cookieid);
        set(13, createip);
        set(14, lastuserid);
        set(15, lastip);
        set(16, upvotes);
        set(17, downvotes);
        set(18, netvotes);
        set(19, lastviewip);
        set(20, views);
        set(21, hotness);
        set(22, flagcount);
        set(23, format);
        set(24, created);
        set(25, updated);
        set(26, updatetype);
        set(27, title);
        set(28, content);
        set(29, tags);
        set(30, name);
        set(31, notify);
    }
}
