/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaSharedevents;
import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaSharedeventsRecord extends TableRecordImpl<QaSharedeventsRecord> implements Record7<String, UInteger, UInteger, UInteger, String, String, Timestamp> {

    private static final long serialVersionUID = -1167298153;

    /**
     * Setter for <code>DBlorg.qa_sharedevents.entitytype</code>.
     */
    public void setEntitytype(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_sharedevents.entitytype</code>.
     */
    public String getEntitytype() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_sharedevents.entityid</code>.
     */
    public void setEntityid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_sharedevents.entityid</code>.
     */
    public UInteger getEntityid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_sharedevents.questionid</code>.
     */
    public void setQuestionid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_sharedevents.questionid</code>.
     */
    public UInteger getQuestionid() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_sharedevents.lastpostid</code>.
     */
    public void setLastpostid(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_sharedevents.lastpostid</code>.
     */
    public UInteger getLastpostid() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_sharedevents.updatetype</code>.
     */
    public void setUpdatetype(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_sharedevents.updatetype</code>.
     */
    public String getUpdatetype() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_sharedevents.lastuserid</code>.
     */
    public void setLastuserid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_sharedevents.lastuserid</code>.
     */
    public String getLastuserid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DBlorg.qa_sharedevents.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>DBlorg.qa_sharedevents.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, UInteger, UInteger, UInteger, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, UInteger, UInteger, UInteger, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return QaSharedevents.QA_SHAREDEVENTS.ENTITYTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return QaSharedevents.QA_SHAREDEVENTS.ENTITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return QaSharedevents.QA_SHAREDEVENTS.QUESTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return QaSharedevents.QA_SHAREDEVENTS.LASTPOSTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return QaSharedevents.QA_SHAREDEVENTS.UPDATETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return QaSharedevents.QA_SHAREDEVENTS.LASTUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return QaSharedevents.QA_SHAREDEVENTS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getEntitytype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getEntityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component4() {
        return getLastpostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUpdatetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLastuserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEntitytype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getEntityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getLastpostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUpdatetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLastuserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord value1(String value) {
        setEntitytype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord value2(UInteger value) {
        setEntityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord value3(UInteger value) {
        setQuestionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord value4(UInteger value) {
        setLastpostid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord value5(String value) {
        setUpdatetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord value6(String value) {
        setLastuserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord value7(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaSharedeventsRecord values(String value1, UInteger value2, UInteger value3, UInteger value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaSharedeventsRecord
     */
    public QaSharedeventsRecord() {
        super(QaSharedevents.QA_SHAREDEVENTS);
    }

    /**
     * Create a detached, initialised QaSharedeventsRecord
     */
    public QaSharedeventsRecord(String entitytype, UInteger entityid, UInteger questionid, UInteger lastpostid, String updatetype, String lastuserid, Timestamp updated) {
        super(QaSharedevents.QA_SHAREDEVENTS);

        set(0, entitytype);
        set(1, entityid);
        set(2, questionid);
        set(3, lastpostid);
        set(4, updatetype);
        set(5, lastuserid);
        set(6, updated);
    }
}
