/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.tables.QaTagwords;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaTagwordsRecord extends TableRecordImpl<QaTagwordsRecord> implements Record2<UInteger, UInteger> {

    private static final long serialVersionUID = -1027560873;

    /**
     * Setter for <code>DBlorg.qa_tagwords.postid</code>.
     */
    public void setPostid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_tagwords.postid</code>.
     */
    public UInteger getPostid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_tagwords.wordid</code>.
     */
    public void setWordid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_tagwords.wordid</code>.
     */
    public UInteger getWordid() {
        return (UInteger) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QaTagwords.QA_TAGWORDS.POSTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return QaTagwords.QA_TAGWORDS.WORDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTagwordsRecord value1(UInteger value) {
        setPostid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTagwordsRecord value2(UInteger value) {
        setWordid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTagwordsRecord values(UInteger value1, UInteger value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaTagwordsRecord
     */
    public QaTagwordsRecord() {
        super(QaTagwords.QA_TAGWORDS);
    }

    /**
     * Create a detached, initialised QaTagwordsRecord
     */
    public QaTagwordsRecord(UInteger postid, UInteger wordid) {
        super(QaTagwords.QA_TAGWORDS);

        set(0, postid);
        set(1, wordid);
    }
}
