/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.tables.QaTagmetas;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaTagmetasRecord extends UpdatableRecordImpl<QaTagmetasRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1801393642;

    /**
     * Setter for <code>DBlorg.qa_tagmetas.tag</code>.
     */
    public void setTag(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_tagmetas.tag</code>.
     */
    public String getTag() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_tagmetas.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_tagmetas.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_tagmetas.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_tagmetas.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return QaTagmetas.QA_TAGMETAS.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QaTagmetas.QA_TAGMETAS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return QaTagmetas.QA_TAGMETAS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTagmetasRecord value1(String value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTagmetasRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTagmetasRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaTagmetasRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaTagmetasRecord
     */
    public QaTagmetasRecord() {
        super(QaTagmetas.QA_TAGMETAS);
    }

    /**
     * Create a detached, initialised QaTagmetasRecord
     */
    public QaTagmetasRecord(String tag, String title, String content) {
        super(QaTagmetas.QA_TAGMETAS);

        set(0, tag);
        set(1, title);
        set(2, content);
    }
}
