/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaUserbadges;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserbadgesRecord extends UpdatableRecordImpl<QaUserbadgesRecord> implements Record6<Timestamp, Integer, Byte, Integer, String, Integer> {

    private static final long serialVersionUID = -1622800887;

    /**
     * Setter for <code>DBlorg.qa_userbadges.awarded_at</code>.
     */
    public void setAwardedAt(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userbadges.awarded_at</code>.
     */
    public Timestamp getAwardedAt() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_userbadges.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userbadges.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_userbadges.notify</code>.
     */
    public void setNotify(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userbadges.notify</code>.
     */
    public Byte getNotify() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_userbadges.object_id</code>.
     */
    public void setObjectId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userbadges.object_id</code>.
     */
    public Integer getObjectId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_userbadges.badge_slug</code>.
     */
    public void setBadgeSlug(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userbadges.badge_slug</code>.
     */
    public String getBadgeSlug() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_userbadges.id</code>.
     */
    public void setId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userbadges.id</code>.
     */
    public Integer getId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Timestamp, Integer, Byte, Integer, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Timestamp, Integer, Byte, Integer, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return QaUserbadges.QA_USERBADGES.AWARDED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return QaUserbadges.QA_USERBADGES.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return QaUserbadges.QA_USERBADGES.NOTIFY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return QaUserbadges.QA_USERBADGES.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return QaUserbadges.QA_USERBADGES.BADGE_SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return QaUserbadges.QA_USERBADGES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getAwardedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getNotify();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBadgeSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getAwardedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getNotify();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBadgeSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserbadgesRecord value1(Timestamp value) {
        setAwardedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserbadgesRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserbadgesRecord value3(Byte value) {
        setNotify(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserbadgesRecord value4(Integer value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserbadgesRecord value5(String value) {
        setBadgeSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserbadgesRecord value6(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserbadgesRecord values(Timestamp value1, Integer value2, Byte value3, Integer value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaUserbadgesRecord
     */
    public QaUserbadgesRecord() {
        super(QaUserbadges.QA_USERBADGES);
    }

    /**
     * Create a detached, initialised QaUserbadgesRecord
     */
    public QaUserbadgesRecord(Timestamp awardedAt, Integer userId, Byte notify, Integer objectId, String badgeSlug, Integer id) {
        super(QaUserbadges.QA_USERBADGES);

        set(0, awardedAt);
        set(1, userId);
        set(2, notify);
        set(3, objectId);
        set(4, badgeSlug);
        set(5, id);
    }
}
