/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.tables.QaUserlimits;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserlimitsRecord extends TableRecordImpl<QaUserlimitsRecord> implements Record4<String, String, UInteger, UShort> {

    private static final long serialVersionUID = 1797725072;

    /**
     * Setter for <code>DBlorg.qa_userlimits.userid</code>.
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userlimits.userid</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_userlimits.action</code>.
     */
    public void setAction(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userlimits.action</code>.
     */
    public String getAction() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_userlimits.period</code>.
     */
    public void setPeriod(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userlimits.period</code>.
     */
    public UInteger getPeriod() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_userlimits.count</code>.
     */
    public void setCount(UShort value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userlimits.count</code>.
     */
    public UShort getCount() {
        return (UShort) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, UInteger, UShort> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, UInteger, UShort> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return QaUserlimits.QA_USERLIMITS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QaUserlimits.QA_USERLIMITS.ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return QaUserlimits.QA_USERLIMITS.PERIOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field4() {
        return QaUserlimits.QA_USERLIMITS.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component4() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value4() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserlimitsRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserlimitsRecord value2(String value) {
        setAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserlimitsRecord value3(UInteger value) {
        setPeriod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserlimitsRecord value4(UShort value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserlimitsRecord values(String value1, String value2, UInteger value3, UShort value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaUserlimitsRecord
     */
    public QaUserlimitsRecord() {
        super(QaUserlimits.QA_USERLIMITS);
    }

    /**
     * Create a detached, initialised QaUserlimitsRecord
     */
    public QaUserlimitsRecord(String userid, String action, UInteger period, UShort count) {
        super(QaUserlimits.QA_USERLIMITS);

        set(0, userid);
        set(1, action);
        set(2, period);
        set(3, count);
    }
}
