/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.tables.QaUserpoints;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserpointsRecord extends UpdatableRecordImpl<QaUserpointsRecord> implements Record16<String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -566363493;

    /**
     * Setter for <code>DBlorg.qa_userpoints.userid</code>.
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.userid</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.points</code>.
     */
    public void setPoints(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.points</code>.
     */
    public Integer getPoints() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.qposts</code>.
     */
    public void setQposts(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.qposts</code>.
     */
    public Integer getQposts() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.aposts</code>.
     */
    public void setAposts(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.aposts</code>.
     */
    public Integer getAposts() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.cposts</code>.
     */
    public void setCposts(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.cposts</code>.
     */
    public Integer getCposts() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.aselects</code>.
     */
    public void setAselects(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.aselects</code>.
     */
    public Integer getAselects() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.aselecteds</code>.
     */
    public void setAselecteds(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.aselecteds</code>.
     */
    public Integer getAselecteds() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.qupvotes</code>.
     */
    public void setQupvotes(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.qupvotes</code>.
     */
    public Integer getQupvotes() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.qdownvotes</code>.
     */
    public void setQdownvotes(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.qdownvotes</code>.
     */
    public Integer getQdownvotes() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.aupvotes</code>.
     */
    public void setAupvotes(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.aupvotes</code>.
     */
    public Integer getAupvotes() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.adownvotes</code>.
     */
    public void setAdownvotes(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.adownvotes</code>.
     */
    public Integer getAdownvotes() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.qvoteds</code>.
     */
    public void setQvoteds(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.qvoteds</code>.
     */
    public Integer getQvoteds() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.avoteds</code>.
     */
    public void setAvoteds(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.avoteds</code>.
     */
    public Integer getAvoteds() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.upvoteds</code>.
     */
    public void setUpvoteds(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.upvoteds</code>.
     */
    public Integer getUpvoteds() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.downvoteds</code>.
     */
    public void setDownvoteds(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.downvoteds</code>.
     */
    public Integer getDownvoteds() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>DBlorg.qa_userpoints.bonus</code>.
     */
    public void setBonus(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userpoints.bonus</code>.
     */
    public Integer getBonus() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return QaUserpoints.QA_USERPOINTS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return QaUserpoints.QA_USERPOINTS.POINTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return QaUserpoints.QA_USERPOINTS.QPOSTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return QaUserpoints.QA_USERPOINTS.APOSTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return QaUserpoints.QA_USERPOINTS.CPOSTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return QaUserpoints.QA_USERPOINTS.ASELECTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return QaUserpoints.QA_USERPOINTS.ASELECTEDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return QaUserpoints.QA_USERPOINTS.QUPVOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return QaUserpoints.QA_USERPOINTS.QDOWNVOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return QaUserpoints.QA_USERPOINTS.AUPVOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return QaUserpoints.QA_USERPOINTS.ADOWNVOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return QaUserpoints.QA_USERPOINTS.QVOTEDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return QaUserpoints.QA_USERPOINTS.AVOTEDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return QaUserpoints.QA_USERPOINTS.UPVOTEDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return QaUserpoints.QA_USERPOINTS.DOWNVOTEDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return QaUserpoints.QA_USERPOINTS.BONUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQposts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAposts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCposts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getAselects();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getAselecteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getQupvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getQdownvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getAupvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getAdownvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getQvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getAvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getUpvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getDownvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getBonus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQposts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAposts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCposts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getAselects();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getAselecteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getQupvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getQdownvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getAupvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getAdownvotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getQvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getAvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getUpvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getDownvoteds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getBonus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value2(Integer value) {
        setPoints(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value3(Integer value) {
        setQposts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value4(Integer value) {
        setAposts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value5(Integer value) {
        setCposts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value6(Integer value) {
        setAselects(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value7(Integer value) {
        setAselecteds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value8(Integer value) {
        setQupvotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value9(Integer value) {
        setQdownvotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value10(Integer value) {
        setAupvotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value11(Integer value) {
        setAdownvotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value12(Integer value) {
        setQvoteds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value13(Integer value) {
        setAvoteds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value14(Integer value) {
        setUpvoteds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value15(Integer value) {
        setDownvoteds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord value16(Integer value) {
        setBonus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserpointsRecord values(String value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaUserpointsRecord
     */
    public QaUserpointsRecord() {
        super(QaUserpoints.QA_USERPOINTS);
    }

    /**
     * Create a detached, initialised QaUserpointsRecord
     */
    public QaUserpointsRecord(String userid, Integer points, Integer qposts, Integer aposts, Integer cposts, Integer aselects, Integer aselecteds, Integer qupvotes, Integer qdownvotes, Integer aupvotes, Integer adownvotes, Integer qvoteds, Integer avoteds, Integer upvoteds, Integer downvoteds, Integer bonus) {
        super(QaUserpoints.QA_USERPOINTS);

        set(0, userid);
        set(1, points);
        set(2, qposts);
        set(3, aposts);
        set(4, cposts);
        set(5, aselects);
        set(6, aselecteds);
        set(7, qupvotes);
        set(8, qdownvotes);
        set(9, aupvotes);
        set(10, adownvotes);
        set(11, qvoteds);
        set(12, avoteds);
        set(13, upvoteds);
        set(14, downvoteds);
        set(15, bonus);
    }
}
