/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.tables.QaUservotes;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUservotesRecord extends TableRecordImpl<QaUservotesRecord> implements Record4<UInteger, String, Byte, Byte> {

    private static final long serialVersionUID = -2046341947;

    /**
     * Setter for <code>DBlorg.qa_uservotes.postid</code>.
     */
    public void setPostid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_uservotes.postid</code>.
     */
    public UInteger getPostid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_uservotes.userid</code>.
     */
    public void setUserid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_uservotes.userid</code>.
     */
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_uservotes.vote</code>.
     */
    public void setVote(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_uservotes.vote</code>.
     */
    public Byte getVote() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_uservotes.flag</code>.
     */
    public void setFlag(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_uservotes.flag</code>.
     */
    public Byte getFlag() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, Byte, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, Byte, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QaUservotes.QA_USERVOTES.POSTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QaUservotes.QA_USERVOTES.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return QaUservotes.QA_USERVOTES.VOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return QaUservotes.QA_USERVOTES.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getVote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getPostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getVote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUservotesRecord value1(UInteger value) {
        setPostid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUservotesRecord value2(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUservotesRecord value3(Byte value) {
        setVote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUservotesRecord value4(Byte value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUservotesRecord values(UInteger value1, String value2, Byte value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaUservotesRecord
     */
    public QaUservotesRecord() {
        super(QaUservotes.QA_USERVOTES);
    }

    /**
     * Create a detached, initialised QaUservotesRecord
     */
    public QaUservotesRecord(UInteger postid, String userid, Byte vote, Byte flag) {
        super(QaUservotes.QA_USERVOTES);

        set(0, postid);
        set(1, userid);
        set(2, vote);
        set(3, flag);
    }
}
