/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaUserevents;
import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUsereventsRecord extends TableRecordImpl<QaUsereventsRecord> implements Record8<String, String, UInteger, UInteger, UInteger, String, String, Timestamp> {

    private static final long serialVersionUID = -1532138169;

    /**
     * Setter for <code>DBlorg.qa_userevents.userid</code>.
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.userid</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_userevents.entitytype</code>.
     */
    public void setEntitytype(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.entitytype</code>.
     */
    public String getEntitytype() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_userevents.entityid</code>.
     */
    public void setEntityid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.entityid</code>.
     */
    public UInteger getEntityid() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_userevents.questionid</code>.
     */
    public void setQuestionid(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.questionid</code>.
     */
    public UInteger getQuestionid() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_userevents.lastpostid</code>.
     */
    public void setLastpostid(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.lastpostid</code>.
     */
    public UInteger getLastpostid() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_userevents.updatetype</code>.
     */
    public void setUpdatetype(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.updatetype</code>.
     */
    public String getUpdatetype() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DBlorg.qa_userevents.lastuserid</code>.
     */
    public void setLastuserid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.lastuserid</code>.
     */
    public String getLastuserid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DBlorg.qa_userevents.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userevents.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, UInteger, UInteger, UInteger, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, UInteger, UInteger, UInteger, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return QaUserevents.QA_USEREVENTS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QaUserevents.QA_USEREVENTS.ENTITYTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return QaUserevents.QA_USEREVENTS.ENTITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return QaUserevents.QA_USEREVENTS.QUESTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return QaUserevents.QA_USEREVENTS.LASTPOSTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return QaUserevents.QA_USEREVENTS.UPDATETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return QaUserevents.QA_USEREVENTS.LASTUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return QaUserevents.QA_USEREVENTS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEntitytype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getEntityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component4() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getLastpostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUpdatetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLastuserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEntitytype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getEntityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getLastpostid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastuserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value2(String value) {
        setEntitytype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value3(UInteger value) {
        setEntityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value4(UInteger value) {
        setQuestionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value5(UInteger value) {
        setLastpostid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value6(String value) {
        setUpdatetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value7(String value) {
        setLastuserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord value8(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUsereventsRecord values(String value1, String value2, UInteger value3, UInteger value4, UInteger value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaUsereventsRecord
     */
    public QaUsereventsRecord() {
        super(QaUserevents.QA_USEREVENTS);
    }

    /**
     * Create a detached, initialised QaUsereventsRecord
     */
    public QaUsereventsRecord(String userid, String entitytype, UInteger entityid, UInteger questionid, UInteger lastpostid, String updatetype, String lastuserid, Timestamp updated) {
        super(QaUserevents.QA_USEREVENTS);

        set(0, userid);
        set(1, entitytype);
        set(2, entityid);
        set(3, questionid);
        set(4, lastpostid);
        set(5, updatetype);
        set(6, lastuserid);
        set(7, updated);
    }
}
