/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import DBlorg.tables.QaUsers;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUsersRecord extends UpdatableRecordImpl<QaUsersRecord> {

    private static final long serialVersionUID = -1533681521;

    /**
     * Setter for <code>DBlorg.qa_users.userid</code>.
     */
    public void setUserid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.userid</code>.
     */
    public UInteger getUserid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_users.sellerid</code>.
     */
    public void setSellerid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.sellerid</code>.
     */
    public Integer getSellerid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_users.owner</code>.
     */
    public void setOwner(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.owner</code>.
     */
    public Byte getOwner() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_users.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_users.createip</code>.
     */
    public void setCreateip(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.createip</code>.
     */
    public UInteger getCreateip() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_users.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DBlorg.qa_users.handle</code>.
     */
    public void setHandle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.handle</code>.
     */
    public String getHandle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DBlorg.qa_users.avatarblobid</code>.
     */
    public void setAvatarblobid(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.avatarblobid</code>.
     */
    public ULong getAvatarblobid() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>DBlorg.qa_users.avatarwidth</code>.
     */
    public void setAvatarwidth(UShort value) {
        set(8, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.avatarwidth</code>.
     */
    public UShort getAvatarwidth() {
        return (UShort) get(8);
    }

    /**
     * Setter for <code>DBlorg.qa_users.avatarheight</code>.
     */
    public void setAvatarheight(UShort value) {
        set(9, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.avatarheight</code>.
     */
    public UShort getAvatarheight() {
        return (UShort) get(9);
    }

    /**
     * Setter for <code>DBlorg.qa_users.passsalt</code>.
     */
    public void setPasssalt(byte... value) {
        set(10, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.passsalt</code>.
     */
    public byte[] getPasssalt() {
        return (byte[]) get(10);
    }

    /**
     * Setter for <code>DBlorg.qa_users.passcheck</code>.
     */
    public void setPasscheck(byte... value) {
        set(11, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.passcheck</code>.
     */
    public byte[] getPasscheck() {
        return (byte[]) get(11);
    }

    /**
     * Setter for <code>DBlorg.qa_users.level</code>.
     */
    public void setLevel(UByte value) {
        set(12, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.level</code>.
     */
    public UByte getLevel() {
        return (UByte) get(12);
    }

    /**
     * Setter for <code>DBlorg.qa_users.loggedin</code>.
     */
    public void setLoggedin(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.loggedin</code>.
     */
    public Timestamp getLoggedin() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>DBlorg.qa_users.loginip</code>.
     */
    public void setLoginip(UInteger value) {
        set(14, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.loginip</code>.
     */
    public UInteger getLoginip() {
        return (UInteger) get(14);
    }

    /**
     * Setter for <code>DBlorg.qa_users.written</code>.
     */
    public void setWritten(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.written</code>.
     */
    public Timestamp getWritten() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>DBlorg.qa_users.writeip</code>.
     */
    public void setWriteip(UInteger value) {
        set(16, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.writeip</code>.
     */
    public UInteger getWriteip() {
        return (UInteger) get(16);
    }

    /**
     * Setter for <code>DBlorg.qa_users.emailcode</code>.
     */
    public void setEmailcode(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.emailcode</code>.
     */
    public String getEmailcode() {
        return (String) get(17);
    }

    /**
     * Setter for <code>DBlorg.qa_users.sessioncode</code>.
     */
    public void setSessioncode(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.sessioncode</code>.
     */
    public String getSessioncode() {
        return (String) get(18);
    }

    /**
     * Setter for <code>DBlorg.qa_users.sessionsource</code>.
     */
    public void setSessionsource(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.sessionsource</code>.
     */
    public String getSessionsource() {
        return (String) get(19);
    }

    /**
     * Setter for <code>DBlorg.qa_users.flags</code>.
     */
    public void setFlags(UShort value) {
        set(20, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.flags</code>.
     */
    public UShort getFlags() {
        return (UShort) get(20);
    }

    /**
     * Setter for <code>DBlorg.qa_users.wallposts</code>.
     */
    public void setWallposts(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.wallposts</code>.
     */
    public Integer getWallposts() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>DBlorg.qa_users.oemail</code>.
     */
    public void setOemail(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>DBlorg.qa_users.oemail</code>.
     */
    public String getOemail() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaUsersRecord
     */
    public QaUsersRecord() {
        super(QaUsers.QA_USERS);
    }

    /**
     * Create a detached, initialised QaUsersRecord
     */
    public QaUsersRecord(UInteger userid, Integer sellerid, Byte owner, Timestamp created, UInteger createip, String email, String handle, ULong avatarblobid, UShort avatarwidth, UShort avatarheight, byte[] passsalt, byte[] passcheck, UByte level, Timestamp loggedin, UInteger loginip, Timestamp written, UInteger writeip, String emailcode, String sessioncode, String sessionsource, UShort flags, Integer wallposts, String oemail) {
        super(QaUsers.QA_USERS);

        set(0, userid);
        set(1, sellerid);
        set(2, owner);
        set(3, created);
        set(4, createip);
        set(5, email);
        set(6, handle);
        set(7, avatarblobid);
        set(8, avatarwidth);
        set(9, avatarheight);
        set(10, passsalt);
        set(11, passcheck);
        set(12, level);
        set(13, loggedin);
        set(14, loginip);
        set(15, written);
        set(16, writeip);
        set(17, emailcode);
        set(18, sessioncode);
        set(19, sessionsource);
        set(20, flags);
        set(21, wallposts);
        set(22, oemail);
    }
}
