/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.tables.QaUserfields;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaUserfieldsRecord extends UpdatableRecordImpl<QaUserfieldsRecord> implements Record6<UShort, String, String, UShort, UByte, UByte> {

    private static final long serialVersionUID = 202859716;

    /**
     * Setter for <code>DBlorg.qa_userfields.fieldid</code>.
     */
    public void setFieldid(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userfields.fieldid</code>.
     */
    public UShort getFieldid() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_userfields.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userfields.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_userfields.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userfields.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_userfields.position</code>.
     */
    public void setPosition(UShort value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userfields.position</code>.
     */
    public UShort getPosition() {
        return (UShort) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_userfields.flags</code>.
     */
    public void setFlags(UByte value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userfields.flags</code>.
     */
    public UByte getFlags() {
        return (UByte) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_userfields.permit</code>.
     */
    public void setPermit(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_userfields.permit</code>.
     */
    public UByte getPermit() {
        return (UByte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UShort> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UShort, String, String, UShort, UByte, UByte> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UShort, String, String, UShort, UByte, UByte> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field1() {
        return QaUserfields.QA_USERFIELDS.FIELDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QaUserfields.QA_USERFIELDS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return QaUserfields.QA_USERFIELDS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field4() {
        return QaUserfields.QA_USERFIELDS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field5() {
        return QaUserfields.QA_USERFIELDS.FLAGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return QaUserfields.QA_USERFIELDS.PERMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component1() {
        return getFieldid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component4() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component5() {
        return getFlags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component6() {
        return getPermit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value1() {
        return getFieldid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value4() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value5() {
        return getFlags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getPermit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfieldsRecord value1(UShort value) {
        setFieldid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfieldsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfieldsRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfieldsRecord value4(UShort value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfieldsRecord value5(UByte value) {
        setFlags(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfieldsRecord value6(UByte value) {
        setPermit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaUserfieldsRecord values(UShort value1, String value2, String value3, UShort value4, UByte value5, UByte value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaUserfieldsRecord
     */
    public QaUserfieldsRecord() {
        super(QaUserfields.QA_USERFIELDS);
    }

    /**
     * Create a detached, initialised QaUserfieldsRecord
     */
    public QaUserfieldsRecord(UShort fieldid, String title, String content, UShort position, UByte flags, UByte permit) {
        super(QaUserfields.QA_USERFIELDS);

        set(0, fieldid);
        set(1, title);
        set(2, content);
        set(3, position);
        set(4, flags);
        set(5, permit);
    }
}
