/*
 * This file is generated by jOOQ.
*/
package DBlorg.tables.records;


import javax.annotation.Generated;

import DBlorg.tables.QaWords;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QaWordsRecord extends UpdatableRecordImpl<QaWordsRecord> implements Record6<UInteger, String, UInteger, UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 1914836459;

    /**
     * Setter for <code>DBlorg.qa_words.wordid</code>.
     */
    public void setWordid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBlorg.qa_words.wordid</code>.
     */
    public UInteger getWordid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>DBlorg.qa_words.word</code>.
     */
    public void setWord(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBlorg.qa_words.word</code>.
     */
    public String getWord() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DBlorg.qa_words.titlecount</code>.
     */
    public void setTitlecount(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>DBlorg.qa_words.titlecount</code>.
     */
    public UInteger getTitlecount() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>DBlorg.qa_words.contentcount</code>.
     */
    public void setContentcount(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>DBlorg.qa_words.contentcount</code>.
     */
    public UInteger getContentcount() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>DBlorg.qa_words.tagwordcount</code>.
     */
    public void setTagwordcount(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>DBlorg.qa_words.tagwordcount</code>.
     */
    public UInteger getTagwordcount() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>DBlorg.qa_words.tagcount</code>.
     */
    public void setTagcount(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>DBlorg.qa_words.tagcount</code>.
     */
    public UInteger getTagcount() {
        return (UInteger) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, UInteger, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, UInteger, UInteger, UInteger, UInteger> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QaWords.QA_WORDS.WORDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QaWords.QA_WORDS.WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return QaWords.QA_WORDS.TITLECOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return QaWords.QA_WORDS.CONTENTCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return QaWords.QA_WORDS.TAGWORDCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return QaWords.QA_WORDS.TAGCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getTitlecount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component4() {
        return getContentcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getTagwordcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component6() {
        return getTagcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getWordid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getTitlecount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getContentcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getTagwordcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getTagcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaWordsRecord value1(UInteger value) {
        setWordid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaWordsRecord value2(String value) {
        setWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaWordsRecord value3(UInteger value) {
        setTitlecount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaWordsRecord value4(UInteger value) {
        setContentcount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaWordsRecord value5(UInteger value) {
        setTagwordcount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaWordsRecord value6(UInteger value) {
        setTagcount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QaWordsRecord values(UInteger value1, String value2, UInteger value3, UInteger value4, UInteger value5, UInteger value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QaWordsRecord
     */
    public QaWordsRecord() {
        super(QaWords.QA_WORDS);
    }

    /**
     * Create a detached, initialised QaWordsRecord
     */
    public QaWordsRecord(UInteger wordid, String word, UInteger titlecount, UInteger contentcount, UInteger tagwordcount, UInteger tagcount) {
        super(QaWords.QA_WORDS);

        set(0, wordid);
        set(1, word);
        set(2, titlecount);
        set(3, contentcount);
        set(4, tagwordcount);
        set(5, tagcount);
    }
}
