/*
 * This file is generated by jOOQ.
*/
package DBnewLogrExtra.tables;


import DBnewLogrExtra.Indexes;
import DBnewLogrExtra.Keys;
import DBnewLogrExtra.Newlogrextra;
import DBnewLogrExtra.tables.records.ClosedRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Closed extends TableImpl<ClosedRecord> {

    private static final long serialVersionUID = -539943493;

    /**
     * The reference instance of <code>DBnewLogrExtra.closed</code>
     */
    public static final Closed CLOSED = new Closed();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClosedRecord> getRecordType() {
        return ClosedRecord.class;
    }

    /**
     * The column <code>DBnewLogrExtra.closed.id</code>.
     */
    public final TableField<ClosedRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.userid</code>.
     */
    public final TableField<ClosedRecord, Integer> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.qsid</code>.
     */
    public final TableField<ClosedRecord, Integer> QSID = createField("qsid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.duplicate</code>.
     */
    public final TableField<ClosedRecord, Byte> DUPLICATE = createField("duplicate", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.original_slug</code>.
     */
    public final TableField<ClosedRecord, String> ORIGINAL_SLUG = createField("original_slug", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.reason</code>.
     */
    public final TableField<ClosedRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.status</code>.
     */
    public final TableField<ClosedRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.created</code>.
     */
    public final TableField<ClosedRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>DBnewLogrExtra.closed.updated</code>.
     */
    public final TableField<ClosedRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>DBnewLogrExtra.closed</code> table reference
     */
    public Closed() {
        this(DSL.name("closed"), null);
    }

    /**
     * Create an aliased <code>DBnewLogrExtra.closed</code> table reference
     */
    public Closed(String alias) {
        this(DSL.name(alias), CLOSED);
    }

    /**
     * Create an aliased <code>DBnewLogrExtra.closed</code> table reference
     */
    public Closed(Name alias) {
        this(alias, CLOSED);
    }

    private Closed(Name alias, Table<ClosedRecord> aliased) {
        this(alias, aliased, null);
    }

    private Closed(Name alias, Table<ClosedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Newlogrextra.NEWLOGREXTRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLOSED_IDX_4C74DE45A90BB43, Indexes.CLOSED_IDX_4C74DE4F132696E, Indexes.CLOSED_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ClosedRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CLOSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClosedRecord> getPrimaryKey() {
        return Keys.KEY_CLOSED_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClosedRecord>> getKeys() {
        return Arrays.<UniqueKey<ClosedRecord>>asList(Keys.KEY_CLOSED_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Closed as(String alias) {
        return new Closed(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Closed as(Name alias) {
        return new Closed(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Closed rename(String name) {
        return new Closed(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Closed rename(Name name) {
        return new Closed(name, null);
    }
}
